### ISSUE TITLE
Restrict commits to k210-related port

### ISSUE THREAD

**Issue by DurandA** [sipeed/MaixPy-v1#1]
It would be very helpful to keep this repository clean with only k210-related additions so it is possible to keep it in sync with the upstream.

The commit 12a5258 contains tons of code related to other ports (e.g. ports/esp32) which is unnecessary and annoying.

**Comment by xiaoxiaohuixxh** [comment]
ou,ths a lot！

**Comment by wipping** [comment]
We have fixed it   ,   ths a lot
