### ISSUE TITLE
IDE bug: script behavior different when pressing the play button

### ISSUE THREAD

**Issue by laurentopia** [sipeed/MaixPy-v1#100]
repro:
1. flash the no_lvlg firmware
2. flash this file [avoidance.zip](https://github.com/sipeed/MaixPy/files/3268033/avoidance.zip)
3. load this in the IDE [boot.zip](https://github.com/sipeed/MaixPy/files/3268034/boot.zip)
4. connect to maix bit and press the play button
=you get this 
![photo_2019-06-07_20-07-08](https://user-images.githubusercontent.com/26075468/59141336-da5df580-895f-11e9-8f3c-198e48956394.jpg)
5. click "save open script to board"
6. reboot the maixpy
= loading of the model with kpu.load passes kpu.load and displays "done"

**Comment by Neutree** [comment]
resolved in latest master branch
