### ISSUE TITLE
IDE: MemoryError after a few press play

### ISSUE THREAD

**Issue by laurentopia** [sipeed/MaixPy-v1#101]
repro:
paste this in the IDE
connect to the bit and press play, stop, play 5 to 10 times
you'll get this
![image](https://user-images.githubusercontent.com/26075468/59141846-f1551580-8968-11e9-8555-04eb12acd6f8.png)

# Untitled - By: laurent - Fri Jun 7 2019

import sensor, image, time, lcd, image

sensor.reset()
sensor.set_pixformat(sensor.RGB565)
sensor.set_framesize(sensor.QVGA)
sensor.skip_frames(time = 2000)

```
lcd.init()
lcd.direction(lcd.YX_LRUD)
clock = time.clock()
img_lcd = image.Image()
while(True):
	clock.tick()
	img = sensor.snapshot()
	#print(clock.fps())
	a= img_lcd.draw_rectangle(100,100,100,16, color = lcd.BLACK, fill=True)
	a= img_lcd.draw_string(100,100,str(clock.fps()),color = (255, 255, 255))
	lcd.display(img_lcd)
```

**Comment by Neutree** [comment]
for the img_lcd is a global variable, in the old firmware, IDE run script in a console mode, that means, the global variable always exists, and maybe gc's problem in old firmware, use the latest master's firmware and IDE will resolve it
