### ISSUE TITLE
IDE: .py only runs once from the editor

### ISSUE THREAD

**Issue by laurentopia** [sipeed/MaixPy-v1#102]
repro:

1. flash no_lvgl
2. flash this
[avoidance.zip](https://github.com/sipeed/MaixPy/files/3268235/avoidance.zip)
3. paste this script in the IDE
[boot.zip](https://github.com/sipeed/MaixPy/files/3268237/boot.zip)
4. press connect
5. press play
= it only displays forward calculated and there are no error indicating that it's stuck
6. press stop
7. press play again
= the screen on the maixbit doesn't change

**Comment by Neutree** [comment]
it seems all normal  operations, just used kpu related operations, just use latest IDE and firmware
