### ISSUE TITLE
IDE BUG: When a boot.py has a problem, IDE can't connect

### ISSUE THREAD

**Issue by laurentopia** [sipeed/MaixPy-v1#103]
repro:
1. install the content of this repo to the maix bit https://github.com/laurentopia/AI-Avoidance
= when the boot.py reboots it'll hang
3. launche MAIXPY IDE and try to connect
= you can't it keeps looping

**Comment by seedsofhope** [comment]
What do you mean boot has a problem?
Ide is not connecting for me anymore... Putty connects, ide does not, on both windows and Ubuntu. My board is maixduino with esp32. Firmware 0.3.2 minimal...
... Sipeed guys, plz fix the ide

**Comment by daryllman** [comment]
@seedsofhope have u solved ur problem? I faced the exact same problem...! help pls

**Comment by laurentopia** [comment]
no i gave up on their stuff

**Comment by daryllman** [comment]
@laurentopia @seedsofhope Just in case you guys are interested and others who visit this thread, what solved the problem for me was to use maixpy firmware **v0.4.0** and above. This solution should be more pertinent to @seedsofhope. The MaixPy IDE would only connect if its this version and above. Found this statement somewhere after diving into the documentation and other resources for quite some time, was not stated explicitly.

You can find the repo of all the firmware versions here:
[https://dl.sipeed.com/MAIX/MaixPy/release/master/](https://dl.sipeed.com/MAIX/MaixPy/release/master/)
