### ISSUE TITLE
Building fails with the latest pushed code

### ISSUE THREAD

**Issue by robert-hh** [sipeed/MaixPy-v1#104]
Error message in the loader:
/home/robert/Downloads/MicroPython/kendryte-toolchain/bin/../lib/gcc/riscv64-unknown-elf/8.2.0/../../../../riscv64-unknown-elf/bin/ld: ./platform/api/lib_sipeed_kpu.a: error adding symbols: file truncated

The problem seems to be the kpu lib

**Comment by Neutree** [comment]
fixed~

**Comment by robert-hh** [comment]
Confirmed. Thank you very much.
