### ISSUE TITLE
SSL for Maix Go

### ISSUE THREAD

**Issue by jayeheffernan** [sipeed/MaixPy-v1#105]
I'm trying to send HTTPS requests from a script on a Maix Go.  It seems there is no support for SSL: the `usocket` library's `IPPROTO_*` constants are missing, and there is no module named `ssl` or `ussl`.

Does the Maix Go support SSL?  If not, will support be added to firmware soon?

Is there an SSL library I can copy to the device, to fill in for the missing `ussl` library?

**Comment by TakuroFukamizu** [comment]
I need it too...
I hope the ussl module included to the  maixpy in the future...

**Comment by AIWintermuteAI** [comment]
Any progress on that one? As people pointed, without HTTPS support MaixPy board cannot be used as a “true” IoT device, because right now IoT clouds like Azure, AWS, Google and others require https connection using ssl.

**Comment by lypanov** [comment]
Any news on this? Massive disappointment to purchase one of these boards in time for my just started programming-vacation only to realize I can't actually even begin the project without first migrating the board to https://github.com/loboris/MicroPython_K210_LoBo

**Comment by updesh31** [comment]
For this I used Adruino ide to program esp8285 and now i am able to send image from Maixpy board to Telegram using SSL.

**Comment by valenzmanu** [comment]
@updesh31  How did you do it? https://github.com/sipeed/MaixPy/issues/105#issuecomment-572131828

**Comment by updesh31** [comment]
share me your mail id i will share both codes for maixpy and wifi......:)

**Comment by junhuanchen** [comment]
The implementation is here, not merged yet.
https://github.com/junhuanchen/MaixPy/commit/ec7506219f7ebd14bac711c8d48d6e4c5bc87191
You can try it first.
https://github.com/junhuanchen/MaixPy/tree/fix_esp8285_recvPkg
Note that this is a test branch, not stable.

**Comment by valenzmanu** [comment]
Thanks @updesh31! mantt89.mv@gmail.com

**Comment by junhuanchen** [comment]
Latest supported.

**Comment by Vigneshprabhu97** [comment]
@junhuanchen Please help me with installing the maixpy ide which supports SSL ,ussl modules

**Comment by valenzmanu** [comment]
@Vigneshprabhu97 I was able to use ussl modules with the firmware in this branch: <br>https://github.com/sipeed/MaixPy/tree/develop

You can follow the build instructions [here](https://github.com/sipeed/MaixPy/blob/develop/build.md). Hope you find it useful.

I used the same MaixPy IDE btw.

**Comment by junhuanchen** [comment]
build firmware / master enable ussl modules

**Comment by Vigneshprabhu97** [comment]
> @Vigneshprabhu97 I was able to use ussl modules with the firmware in this branch:
> https://github.com/sipeed/MaixPy/tree/develop
> 
> You can follow the build instructions [here](https://github.com/sipeed/MaixPy/blob/develop/build.md). Hope you find it useful.
> 
> I used the same MaixPy IDE btw.

If You have any maixpy scripts for IoT please do share me vigneshprabhu156@gmail.com

**Comment by ReginaldSourn** [comment]
> share me your mail id i will share both codes for maixpy and wifi......:)

Please @updesh31 I need your solutions too. sourn.rithy@gmail.com
