### ISSUE TITLE
"OSError:" printed after gc.collect()

### ISSUE THREAD

**Issue by robert-hh** [sipeed/MaixPy-v1#106]
The first time(s) after cold- or warmstart that gc.collect() is executed, the system prints a message "OSError:", but raises no exception. It does not matter whether the garbage collection is called manually or executed implicitly. Manual example:
```
MicroPython v0.3.2-30-g518c3d5b2-dirty on 2019-06-12; Sipeed_M1 with kendryte-k210
Type "help()" for more information.
>>> import gc
>>> gc.collect()
OSError: 
```

**Comment by Neutree** [comment]
fixed, refer to https://github.com/sipeed/MaixPy/commit/d623eedaa7fff414a073ebe88dcc75b451e24853
