### ISSUE TITLE
[MAIXPY]kpu: load error: -1

### ISSUE THREAD

**Issue by nmk456** [sipeed/MaixPy-v1#107]
I'm trying to figure out how to use the KPU in MaixPy, but when I run the [example code](https://github.com/sipeed/MaixPy_scripts/blob/master/machine_vision/demo_find_face.py) with the only modifications being different anchors and a different model (which is still less than 3 MB) on the SD card, it doesn't load the model and gives the error in the title.

**Comment by Neutree** [comment]
issue out of date, try latest master build, open new issue if some problem
