### ISSUE TITLE
REQUESTION: add urllib or equivalent

### ISSUE THREAD

**Issue by laurentopia** [sipeed/MaixPy-v1#108]
So we can talk to the outside world and serve a web page

**Comment by robert-hh** [comment]
You can find suitable code made for MicroPython at https://github.com/pfalcon/micropython-lib. You may have to adapt it a little bit to the MaixPy dialect.

**Comment by laurentopia** [comment]
thank you

**Comment by Neutree** [comment]
I closed this issue, if some problem, just reopen it
