### ISSUE TITLE
OSERROR "boot.py" "init.py"

### ISSUE THREAD

**Issue by Deus1223** [sipeed/MaixPy-v1#11]
My platform is Sipeed M1W and its LCD display white screen after I burned the [demo](https://github.com/kendryte/kendryte-standalone-demo/tree/master/hello_world).
Then I built and compiled MaixPy and burned micropython.bin to the board but it's still white and display following message on the terminal.

```
Official Site:http://www.sipeed.com/
Wiki:http://maixpy.sipeed.com/
[MAIXPY]Pll0:freq:320666666
[MAIXPY]Pll1:freq:159714285
[MAIXPY]Flash:0xc8:0x17
[MAIXPY]:Spiffs Mount successful 
Traceback (most recent call last):
  File "boot.py", line 14, in <module>
  File "init.py", line 4, in <module>
OSError: [Errno 5] EIO

MicroPython d58620d on 2018-12-11; Sipeed_M1 with kendryte-k210
Type "help()" for more information.
>>> 
```

How to fix it?

**Comment by xiaoxiaohuixxh** [comment]
If this is the first time the machine is powered up, it is recommended to re-burn the latest firmware.
If this is not the first time the machine is powered on, check if the two files exist in the root directory. The mpy boot will execute the two files by default. It can be used to implement a boot script. If it does not exist, it will not affect the execution of the machine. Thank you for your feedback!
