### ISSUE TITLE
[LVGL] Set the image source of lv_img as a variable through python failed

### ISSUE THREAD

**Issue by xiangweizeng** [sipeed/MaixPy-v1#111]
I need to set the picture source of lv_img as a variable through python, but I did not find the binding of lv_img_dsc_t in python binding.
```python
img = lv.img(scr)
img.align(scr, lv.ALIGN.CENTER, 0, 0)
img_dsc = lv.img_dsc_t({
    'header':{
        'always_zero': 0,
        'w':100,
        'h':75,
        'cf':lv.img.CF.TRUE_COLOR
    },
    'data_size': len(img_data),
    'data': img_data
})

img.set_src(img_dsc)
```
report error, AttributeError: 'module' has no attribute 'img_dsc_t'.

Thank you!

**Comment by Neutree** [comment]
out of date, the latest firmware do have this member: https://github.com/sipeed/MaixPy_scripts/blob/master/application/lvgl/lvgl_img.py
