### ISSUE TITLE
Rebuilding the FS

### ISSUE THREAD

**Issue by robert-hh** [sipeed/MaixPy-v1#116]
After I have now managed to rebuild the images, I have two one topic:
1. How do I include other python scripts in the image. Just copying them to .../MaixPy/components/micropython/port/builtin_py an rebuilding is not sufficient.

I found build.make in MaixPy/projects/maixpy_k210/build/micropython/CMakeFiles/micropython.dir, but that looks like an created file.

**Comment by Neutree** [comment]
just copy them to `components/micropython/port/builtin_py` is right, and execute `python3 project.py rebuild`

**Comment by Neutree** [comment]
The makefiles is generated from cmake in the new construction system, so do not edit the makefiles manually.
And you have to format your file system by `os.flash_format()` first for some reason (file path change in source maixpy code)

**Comment by robert-hh** [comment]
Thanks. I found flash_format().
Still there is a hiccup: If I change a file in components/micropython/port/builtin_py, `python3 project.py rebuild` will not rebuild that changed file. I have to use clean and build.

**Comment by robert-hh** [comment]
Hiccup gone. Thanks.
