### ISSUE TITLE
Spiffs: inconsistencies with relative file names

### ISSUE THREAD

**Issue by robert-hh** [sipeed/MaixPy-v1#117]
The handling of relative file names of the spiffs file system of /flash is inconsistent. While
open() accepts relative file names, most os calls require an absolute path.

**Comment by robert-hh** [comment]
I updated the special sipeed version of  pye_mp.py which avoids this file or path name trap. It also is more efficient in loading and saving file on flash, at the cost of the maximal file size, which is about 2500 lines.
https://github.com/robert-hh/K210-Stuff/blob/master/pye.py

**Comment by robert-hh** [comment]
It looks better now. Thanks.

**Comment by Neutree** [comment]
If your pye.py better, you can create PR, thanks~~~
