### ISSUE TITLE
摄像头输出帧大小什么时候可以支持更大的？

### ISSUE THREAD

**Issue by roamboy** [sipeed/MaixPy-v1#118]
摄像头输出帧大小什么时候可以支持更大的？

**Comment by Neutree** [comment]
master分支已经支持了，还没发release

**Comment by roamboy** [comment]
谢谢，那是要去下载master烧录新image这样子吗，会不会变砖master分支，测试过2019.7.6号的编译bin似乎不支持更大的呢，2019.7.9的似乎连接不上呢

**Comment by Neutree** [comment]
烧录maixpy固件不会变砖
