### ISSUE TITLE
doesn't support grayscale image

### ISSUE THREAD

**Issue by maxwelllls** [sipeed/MaixPy-v1#119]
my board is Maix Go,the image display well in RGB565.
When I set pixel format to GRAYSCALE,the image look like this
![image](https://user-images.githubusercontent.com/51860539/60813033-649ab300-a1c5-11e9-8136-b067e4dd0eee.png)

**Comment by Neutree** [comment]
grayscale is not supported in v0.3.2, but supported in master branch, or wait for the next release

**Comment by Neutree** [comment]
fixed in latest master build
