### ISSUE TITLE
How to generate the "cfg.bin" and the "model.bin" file?

### ISSUE THREAD

**Issue by jamescheng-taoyuan** [sipeed/MaixPy-v1#12]
I'd like to try detecting other visual objects by replacing the model-related portion of the machine.face_detect() implementation. I saw that the "cfg.bin" and the "model.bin" data will be read in the init function in the "face_detect.c" file. I've tried Kendryte's model compiler and it can output an "model.bin" file. However, I don't know how to create the "cfg.bin" file. Could you tell me the correct way to generate these files?

**Comment by wipping** [comment]
Sorry，replyu so late.
About your question, we are not sure how to solve it at present.We just got the bin file from the official.But we will solve this question later
