### ISSUE TITLE
ESP32 module

### ISSUE THREAD

**Issue by leozlee** [sipeed/MaixPy-v1#120]
Is there any demo about how to use esp32 on maixduino?
I can onlt find a demo about adc read in eps32, but nothing about network

**Comment by leozlee** [comment]
Try this:https://github.com/micropython/micropython/blob/master/docs/esp32/tutorial/intro.rst

**Comment by chegewara** [comment]
@leozlee There was no API for network on esp32, maybe my PR will be merged to add API.

**Comment by vagoverso** [comment]
There is still no API for network on esp32 :( . I create a socket, i send data but I have no data back.

**Comment by chegewara** [comment]
@vagoverso It is already merged to master, so it should works now.
See this example
https://github.com/sipeed/MaixPy/pull/126
