### ISSUE TITLE
MICROPY_PY_THREAD (1) build issue

### ISSUE THREAD

**Issue by olahBalazs** [sipeed/MaixPy-v1#121]
I have a build script (attached if you are interested
[build_script.zip](https://github.com/sipeed/MaixPy/files/3390421/build_script.zip)
).

I tried to enable the multi threading. I edited the file MaixPy/components/micropython/port/include/mpconfigport.h like:

```
#define MICROPY_PY_THREAD                   (1)
#define MICROPY_PY_THREAD_GIL               (1)
```

Then when I tried to build I got the following error:
![df82CFeJJ7](https://user-images.githubusercontent.com/7669083/61189188-5dbee500-a68a-11e9-8b36-4ba8849128d7.png)
Error: Implicit declaration of function  'free'

The error location is: MaixPy/components/micropython/port/src/mpthreadport.c line 190 column 9.

I then edited the file: MaixPy/components/micropython/port/src/mpthreadport.c  added
`#include <stdlib.h>`
at the top. Then the build successfully finished. Would it be possible to add this fix to the repo? Does anybody else have this issue?

By making a self build I lost the cpufreq python module. Does anybody know where I can re-enable it?

**Comment by Neutree** [comment]
The Freertos from Kendryte have some problems, so we disabled it currently

**Comment by Neutree** [comment]
enable it in menuconfig `python project.py menuconfig` now
