### ISSUE TITLE
AttributeError: 'socket' object has no attribute 'write'

### ISSUE THREAD

**Issue by dahanzimin** [sipeed/MaixPy-v1#128]
AttributeError: 'socket' object has no attribute 'write'
socket库计划啥时候完善更新

**Comment by Neutree** [comment]
可以使用 socket.send

**Comment by dahanzimin** [comment]
需要完整的socke库，来做urequests库

**Comment by junhuanchen** [comment]
这并不是问题，request 只涉及到 send 和 recv ，我们大部分情况下并没有实现 bind 这个接口。
