### ISSUE TITLE
Python命名规范问题

### ISSUE THREAD

**Issue by mushroom-x** [sipeed/MaixPy-v1#13]
类的开头要大写， 缩写也尽量大写 例如： ”LED“，“OV2640”

**Comment by xiaoxiaohuixxh** [comment]
正在考虑驱动有没有必要每一个驱动都新建一个主模块。请问有什么好的建议吗？

**Comment by Singein** [comment]
可以提供统一泛化的接口，比如lcd，可以创建Display模块，在这里实现lcd底层驱动，提供显示相关的统一接口，这样可以之后拓展和兼容其他的显示设备。

**Comment by EzFavorites** [comment]
对于摄像头驱动，你们移植过openmv,可以像openmv那样，把所有摄像头再一次封装，每一种给一个不同的id,用来初始化

**Comment by xiaoxiaohuixxh** [comment]
这个后期可以考虑一下。

**Comment by snowyu** [comment]
esp8266的micropython可以参考，还可以参考MicroBIt的microPython的扩展方式: 

* https://github.com/micropython/micropython/blob/master/ports/esp8266/modules/
* https://github.com/bbcmicrobit/micropython
* https://microbit.org/zh-CN/guide/python/
