### ISSUE TITLE
Feature Request : array library

### ISSUE THREAD

**Issue by narduzzi** [sipeed/MaixPy-v1#137]
Would it be possible to integrate the "array" library for MicroPython in the next release?

**Comment by Neutree** [comment]
did you mean numpy.array? we won't add it

**Comment by Neutree** [comment]
actually micropython indeed have array module, we can add it later

**Comment by Neutree** [comment]
try this one : http://dl.sipeed.com/MAIX/MaixPy/release/master/maixpy_v0.4.0_27_gab68316/
