### ISSUE TITLE
MicroPython开发规范-machine模块

### ISSUE THREAD

**Issue by mushroom-x** [sipeed/MaixPy-v1#14]
MicroPython的machine模块是为了兼容不同的硬件，提供统一的一套API，弱化不同硬件的差异。
machine模块应该只存放基础的硬件操作的API， 其他maixpy特有的功能硬件资源， 可以考虑单独创建一个模块叫做 maixpy

另外人脸检测的部分也不适合放在里面

**Comment by xiaoxiaohuixxh** [comment]
好的，我们会在后面做出对应的修改，谢谢！

**Comment by mushroom-x** [comment]
:smile:
