### ISSUE TITLE
how to support kendryte kd233 board

### ISSUE THREAD

**Issue by jmpty** [sipeed/MaixPy-v1#141]
how to support kendryte kd233 board

**Comment by jmpty** [comment]
download MaixPy bin to kd233 over ,open  MaixPy IDE  connect ok run fail

**Comment by Neutree** [comment]
most of features on kd233 and maix the same, except uart reset and boot logic(DTR RTS),  and you can use it the same as maix GO

**Comment by jmpty** [comment]
有没办法改 板子支持啊

**Comment by Neutree** [comment]
IDE和kflash_gui都有kd233的选项

**Comment by noahzhy** [comment]
连接的上，但是像sensor 无法正常工作

**Comment by Neutree** [comment]
@noahzhy 摄像头么, maixpy暂时只支持0v2640和0v7740还有gc0328

**Comment by noahzhy** [comment]
不光是摄像头，还有sd卡挂载等也有问题

**Comment by Neutree** [comment]
好吧,暂无计划支持

**Comment by LiuXinyu12378** [comment]
LCD也不支持啊
