### ISSUE TITLE
REPL里面 CTRL+E无法进入粘贴模式

### ISSUE THREAD

**Issue by mushroom-x** [sipeed/MaixPy-v1#15]
另外vi模块建议去除

**Comment by xiaoxiaohuixxh** [comment]
vi模块已经在项目代码里去除掉了，后面我们所有的代码都会严格按照license来操作，借此给大家道歉！

**Comment by xiaoxiaohuixxh** [comment]
repl我们现在的支持还不完善。

**Comment by mushroom-x** [comment]
:star: x5

**Comment by robert-hh** [comment]
See also this commit: https://github.com/sipeed/MaixPy/pull/33/commits/411cf73d778cba51c9755c2bc3fc8d4eb5ea1130
