### ISSUE TITLE
TypeError: unexpected keyword argument 'force'

### ISSUE THREAD

**Issue by neofuturism** [sipeed/MaixPy-v1#158]
I tried running the demo_video_play.py example, but I keep on getting this error, 
TypeError: unexpected keyword argument 'force'

I haven't been able to resolve it, 
can you help me, 

Thanks

**Comment by Neutree** [comment]
remove that parameter or upgrade firmware

**Comment by neofuturism** [comment]
Wow, thank you for your quick reply, it did work, 
I will upgrade the firmware too, 

I have another question about running nncase on a mac, should mark this as solved and post a new one?
