### ISSUE TITLE
machine.GPIO修改为machine.Pin

### ISSUE THREAD

**Issue by mushroom-x** [sipeed/MaixPy-v1#16]
创建管脚的时候 类名建议与micropython兼容， 改用”Pin“

另外maixpy的board_info存放了一些管脚的映射， 这个是自定义的么？MicroPython的话， 建议放在Pin下。

**Comment by mushroom-x** [comment]
模块和变量名尽量做到兼容， 这样代码在不同硬件间的移植会容易一些。也更方便MaixPy创建自己的生态。

举例：
* machine.timer -> machine.Timer
* machine.pwm -> machine.PWM
* machine.GPIO -> machine.Pin

**Comment by xiaoxiaohuixxh** [comment]
好的，board_info是板载信息的意思，maixpy上没有pin这一个模块的，因为k210上面的是fpioa，所以我们只有fpioa模块哦，由fpioa模块来负责定义这一个pin是一个什么功能的引脚。

**Comment by mushroom-x** [comment]
了解了， 感谢
