### ISSUE TITLE
哪可以看到腳位圖(包括哪些已經用去)

### ISSUE THREAD

**Issue by crouse12** [sipeed/MaixPy-v1#163]
請問，哪裡可以找到maixbit的腳位表
可以顯示
哪些腳位可以INPUT  OUTPUT PWM ADC
哪些腳位拿去給螢幕  哪些腳位被攝影鏡頭使用

**Comment by Neutree** [comment]
https://wiki.sipeed.com/zh/#
or dl.sipeed.com

**Comment by crouse12** [comment]
沒看到圖片    我要的是這種
這樣才知道哪些腳位可以當數位寫入  哪些可以類比讀取
哪些腳位已經給lcd

![下載](https://user-images.githubusercontent.com/25700616/65374259-7404a500-dcba-11e9-9f23-72c639deb9d2.jpg)

**Comment by Neutree** [comment]
你可能是想要这种图片？
![image](https://user-images.githubusercontent.com/8625829/65397719-ff7a5500-dde4-11e9-8b32-b786a28e12ce.png)



Bit 请看原理图： http://dl.sipeed.com/MAIX/HDK/Maix-Bit ， bit没有画过这样的图片

**Comment by crouse12** [comment]
是  maixbit沒有還蠻怪的  但可以參考這個  真是太好了
另外可以請教一下  maixbit的WIFI網路  camera 和螢幕  用掉了那些腳位
你給的原理圖  有看沒有懂   ........
