### ISSUE TITLE
M5stickV播放avi视频没有声音

### ISSUE THREAD

**Issue by ZeyoPendragon** [sipeed/MaixPy-v1#169]
M5stickV使用video类播放视频（wiki里提供的badapple）只有画面没有声音；
单独使用audio类播放wav音频能够正常出声；
固件版本：maixpy_v0.4.0_50_gcafae9d_m5stickv；

**Comment by Neutree** [comment]
@MarsTechHAN

**Comment by junhuanchen** [comment]
使用最新0.5+固件，有问题可以重新打开issue
