### ISSUE TITLE
network模块的实现

### ISSUE THREAD

**Issue by mushroom-x** [sipeed/MaixPy-v1#17]
建议使用network模块， 待大佬实现。
文档里wifi对象的创建是跟esp8285模块耦合的， 能不能通过network
创建呢？ 弱化esp8285
```python
wifi=machine.esp8285()
wifi.init("your_ssid","your_password")# 连接wifi。
````

> ps: 文档里这两行错位了

**Comment by mushroom-x** [comment]
http://maixpy.sipeed.com/exploreMaixPy/socket/usocket.html

文档链接，没对齐

**Comment by xiaoxiaohuixxh** [comment]
可以的，但是我们还是打算保留esp8285这一个驱动，但是会添加network模块作为一个通用的模块。

**Comment by mushroom-x** [comment]
ok
