### ISSUE TITLE
kflash_gui error: attempting to use a port that is not open

### ISSUE THREAD

**Issue by jeancf** [sipeed/MaixPy-v1#171]
To try and address [this issue](https://github.com/sipeed/MaixPy/issues/170) I wanted to know if upgrading the MaixPy firmware to v0.4 would fix the issue.

When I ran kflash_gui with elevated privileges

![Screenshot_20191006_202349](https://user-images.githubusercontent.com/885845/66273830-ead39d80-e877-11e9-83f2-c16c881c3fdd.png)

I got the following error:

![Screenshot_20191006_203131](https://user-images.githubusercontent.com/885845/66273871-8107c380-e878-11e9-90fd-1aa5aa58e279.png)

So at this stage I really don't know what else to do to start using my MAiXDUiNO.

**Comment by robert-hh** [comment]
Do you have any other application using /dev/ttyUSB0? When ouy say elevated privileges, does it mean you run as sudo?

**Comment by jeancf** [comment]
I run it with sudo indeed and no other application is running.

**Comment by Coffee-Boyy** [comment]
I had an issue where my board only accepted a Baudrate of 115,200. See if changing to that speed works

**Comment by jeancf** [comment]
@ConnorChristie I tried several slower options with no luck.

Does your board have the RX K210 LED constantly on as soon as you power it up?

**Comment by jeancf** [comment]
Board was defective.
