### ISSUE TITLE
Where can I find the source code for lib_sipeed_kpu.a?

### ISSUE THREAD

**Issue by hjiawei** [sipeed/MaixPy-v1#177]
Apologize if this has been asked before or it is in the document. I have searched all repositories under Sipeed organization but I haven't found any. Can someone point me in the right direction?

**Comment by smuehlst** [comment]
Same issue with `lib_mic.a` which is also only available in binary form.

**Comment by Neutree** [comment]
sorry,  lib source code is not open for enrypt model
lib_mic.a is not open yet too
