### ISSUE TITLE
kflash gui error - No such file or directory when trying to burn .kmodel packaged in .kfpkg

### ISSUE THREAD

**Issue by anku2424** [sipeed/MaixPy-v1#179]
Greetings, I was trying to burn my mobilenet v1 model that i trained via transfer learning on Sipeed Maix Dock. I packaged it in .kfpkg file with a flash-list.json specifying the address of the kmodel. I used the maixpy_v0.3.2_minimum.bin firmware. First i downloaded the firmware on the board and it successfully gets downloaded. But when i try to burn the .kfpkg file via kflash_gui i get this error -
No such file or directory: 'C:\Users\user_name\AppData\Local\Temp\tgmslflsdag8kl\flash-list.json
How can i resolve this? TIA.

**Comment by Neutree** [comment]
upgrade to the latest, if problem remain exist,  reopen this issue please~
