### ISSUE TITLE
uos的文件路径问题

### ISSUE THREAD

**Issue by mushroom-x** [sipeed/MaixPy-v1#18]
在文档里有说：
http://maixpy.sipeed.com/exploreMaixPy/uos/uos.html
> “/”非常重要，记得写文件名的时候记得加入

实际上不加也可以， 在打开写入文件的时候， 文件路径不加”/“也可以， 感觉有点冗余。根路径下的文件操作不必要以/开头。或者是说固件已经解决了这个问题，文档还没更新？

**Comment by xiaoxiaohuixxh** [comment]
后面版本的开发加入vfs的支持，wiki更新还有点不同步哦，最新的wiki会在blog.sipeed.com发布
