### ISSUE TITLE
Feature request: Enhanced „Neopixel“

### ISSUE THREAD

**Issue by chmondkind** [sipeed/MaixPy-v1#183]
Hi, thank you for your great work!

Would it be possible to use the micropython neopixel module? It has more options and also supports RGBW led‘s too.
If it‘s used outside of uP, there are other drivers out there.

I saw you don‘t „bitbang“ out and instead use peripherals - is this a must?

I could do some work on this and push it - but I am not sure if and when I could do so. Also it needs to be in-line with the one used now, as it would otherwise break working code.

**Comment by Neutree** [comment]
ws2812 is supported: https://github.com/sipeed/MaixPy_scripts/tree/master/modules/grove/ws2812
