### ISSUE TITLE
no lvgl in v0.4.0 firmware?

### ISSUE THREAD

**Issue by jeancf** [sipeed/MaixPy-v1#184]
I installed MaixPy v0.4.0 on my Maixduino board. When trying to run the lvgl demo (button.py) I get this error:
```
ImportError: no module named 'lvgl'
```
It is not clear from the naming of the bin file (`maixpy_v0.4.0_50_gcafae9d.bin`) if it is included or not. If it is not, how to get it?

**Comment by Neutree** [comment]
download the firmware end with 'lvgl'

Or build your own firmware accoring to build.md or compile online at https://www.maixhub.com/compile.html ,  and select lvgl component
