### ISSUE TITLE
os.listdir()的问题

### ISSUE THREAD

**Issue by EzFavorites** [sipeed/MaixPy-v1#19]
运行os.listdir()会有一些问题，但是增加了一个os.ls()命令，它的结果是正常的。能不能把这两个合二为一，只保留一个标准的os.listdir()。

**Comment by xiaoxiaohuixxh** [comment]
我当初的想法是使用ls()尝试兼容linux的操作习惯，lsdir是mpy标准的一个函数，ls（）函数可以直接得到一个元组形式的文件列表。请问这样的做法合适吗？欢迎提交您的建议！

**Comment by EzFavorites** [comment]
我觉得可以给lsdir()设置一个参数，把这两个整合到一起。由于第一个版本运行os.listdir()会有一些问题，而ls没有问题，就比较好奇，你这么说，感觉也是可以接受的
