### ISSUE TITLE
Looking for help, Try to increase speed of SDcard/TFcard  ；寻找帮助，尝试提高sd卡/tf卡写入速度

### ISSUE THREAD

**Issue by ZSYAD** [sipeed/MaixPy-v1#195]
The speed of SDcard is too slow, i want to record a video  to SDcard, the max frame rate is 12fps。

I find a strange code in sdcard.c :
static void sd_lowlevel_init(uint8_t spi_index)
{
gpiohs_set_drive_mode(SD_CS_PIN, GPIO_DM_OUTPUT);
spi_set_clk_rate(SD_SPI_DEVICE, 200000); /set clk rate/
}

Maybe the speed of SDCard are limited by this code.
Change 200000 to 10000000 may increase the speed
I want to change this code and rebuild to verify my guess, but i can not rebuild it. Could anyone help me to change this code and rebuild it?  Thanks very much.

我想往sd卡里写入视频，但是速度太慢，帧率太低，我发现源码中有一处代码可能限制了SD卡的速度，就是上面的代码中spi_set_clk_rate(SD_SPI_DEVICE, 200000)，我想把200000改成10000000，然后重新build一下，但是我这边没有build的环境，搭建起来较为麻烦，请问有人已经搭建好build环境吗，可以帮我build一下吗？感激不尽

**Comment by Neutree** [comment]
SD的性能不一, 如果需要修改,可以按照 build.md 中所述对源码进行构建即可, 在 linux 或者macOS下编译,网络好的情况(最好有梯子)下很快就能构建成功

**Comment by Neutree** [comment]
我先把issue关闭了,如果仍然存在问题,可以重新打开
