### ISSUE TITLE
请问什么函数可以把摄像头左转或者右转90度

### ISSUE THREAD

**Issue by guojunlu** [sipeed/MaixPy-v1#196]
只有翻转和镜像，请问什么函数可以把摄像头左转或者右转90度

**Comment by AIWintermuteAI** [comment]
Hi! Use rotation_corr from OpenMV
img = img.rotation_corr(z_rotation=90.0)
https://maixpy.sipeed.com/zh/libs/machine_vision/image.html#imgrotationcorrxrotation00-yrotation00-zrotation00-xtranslation00-ytranslation00-zoom10

**Comment by Neutree** [comment]
翻转和镜像是硬件完成的,旋转90只能通过更换摄像头(硬件), 或者通过上面 @AIWintermuteAI  所说的函数旋转
