### ISSUE TITLE
Small issue with ANSI colors

### ISSUE THREAD

**Issue by loboris** [sipeed/MaixPy-v1#20]
There is a small bug in using ANSI colors in `Makefile` files in **test-offical-standardalone-dev** branch.
In function `mod_echo_func` `@echo -e "\033....` should be used, not `@echo "\033....`.
Also the `@echo` in the function should end with reseting the color with `"\033[;0m"`.

BTW, very nice work on this branch.

**Comment by xiaoxiaohuixxh** [comment]
i will fixed it
