### ISSUE TITLE
OSError: Reset Failed

### ISSUE THREAD

**Issue by rosariomoscato** [sipeed/MaixPy-v1#200]
Hello everybody,
trying to run the "Hello World Example" on Maixpy Dock FW version **maixpy_v0.3.2_full** using MaixPy IDE 0.2.3, but always get OSError: Reset Failed.
Can anyone help? PLEASEEEEE

Thank you

**Comment by RaulSokolova** [comment]
I had the same error , it was solved by re-connecting the camera.

**Comment by rosariomoscato** [comment]
@TheImmigrant Thank you so much for yor reply. Actually I fixed the problem updating the firmware to the latest version.

**Comment by bwellmeshed** [comment]
> @TheImmigrant Thank you so much for yor reply. Actually I fixed the problem updating the firmware to the latest version.

Which latest firmware did you use?

**Comment by rosariomoscato** [comment]
maixpy_v0.5.0_12_g284ce83

**Comment by Neutree** [comment]
most is firmware too old or hardware connection problem, or camera sensor broken, or firwamre not support your hardware, currently ov2640 gc0328 0v7740 is supported
