### ISSUE TITLE
Unable to create folder in maixduino

### ISSUE THREAD

**Issue by sasilva1998** [sipeed/MaixPy-v1#208]
I am trying to create a folder inside /flash in a maixduino using rshell, however I can't, I would like to know if it isn't possible or is it that rshell can't do it. I can copy scripts and everything but not to create folders.

**Comment by robert-hh** [comment]
The littlefs variant of maixpy does not support folders.

**Comment by sasilva1998** [comment]
````
 >>> os.mkdir('dir')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NotImplementedError: SPIFFS not support
````

Just tried it via the repl and got this, thanks for the response.

**Comment by Neutree** [comment]
SPIFFS is not support folder but SD card with FAT format do
