### ISSUE TITLE
upip and ussl not supported

### ISSUE THREAD

**Issue by sasilva1998** [sipeed/MaixPy-v1#209]
I need to install some libraries with upip, however it doesn't come included in maixpy, how can I get it inside?

I even tried just to put all upip scripts in so that I could maybe use it, however I need ussl as well, which doesn't come in it. Is there a way in which all this can be done? thanks for the help.

**Comment by lypanov** [comment]
ussl issue is also referred to in https://github.com/sipeed/MaixPy/issues/105 

Unfortunately MaixPy doesn't seem to be a maintained product. An alternative could be https://github.com/loboris/MicroPython_K210_LoBo but I haven't yet managed to find the time to run the (poorly documented) install instructions. Regret purchasing my k210.

**Comment by junhuanchen** [comment]
upip did not test.

ussl in https://github.com/sipeed/MaixPy/tree/develop.

you can compile it yourself.

![image](https://user-images.githubusercontent.com/32978053/86220326-06c16100-bbb6-11ea-944d-856e421064de.png)

**Comment by valenzmanu** [comment]
Tried in develop branch but host name is not supported https://github.com/sipeed/MaixPy/issues/283

**Comment by junhuanchen** [comment]
master support https.

maybe upip need test~

**Comment by junhuanchen** [comment]
master support https.

maybe upip need test~
