### ISSUE TITLE
可以在MaixPy中編譯c/cpp的程式碼

### ISSUE THREAD

**Issue by Deus1223** [sipeed/MaixPy-v1#21]
剛接觸這塊領域不是很確定能不能問這類問題，
在MaixPy目錄底下有看到sdk想問是能直接編譯c語言的意思嗎?
如果可以的話想問問編譯方式或指令之類的

**Comment by xiaoxiaohuixxh** [comment]
您说的是在python里编译c、cpp？还是在这个项目里写c，cpp？底层代码就是用c来编写的。

**Comment by Deus1223** [comment]
在python環境中編譯

**Comment by xiaoxiaohuixxh** [comment]
不支持这个功能哦，因为工程里没有c和cpp的编译链

**Comment by Neutree** [comment]
python层面只能使用python的语言，不能用c/cpp，要用c请编译MAIXPY源码
