### ISSUE TITLE
Wifi maix dock

### ISSUE THREAD

**Issue by krishnak** [sipeed/MaixPy-v1#210]
I received the Maix Dock with factory firmware MicroPython v0.4.0-87-g42e92b235-dirty on 2019-11-07; Sipeed_M1 with kendryte-k210, when the board was powered on it will show ESP_4xxx in the list and I could connect to it and do a PING from the connected to the ESP access point

I downloaded maixpy_v0.5.0_12_g284ce83.bin and flashed the board,

Now the version is MicroPython v0.5.0-12-g284ce83 on 2019-12-31; Sipeed_M1 with kendryte-k210

However the Wifi beacon is no longer appearing on Wifi scans. How to get it back?

**Comment by Neutree** [comment]
I tried latest firmware and demo https://github.com/sipeed/MaixPy_scripts/blob/master/network/demo_wifi_ap_scan.py , it's ok

![image](https://user-images.githubusercontent.com/8625829/89600706-42c2a280-d895-11ea-8a8b-ef92b4f3f717.png)

maybe you forgot connect antenna?

I'll close this issue, if problem remain exist, reopen it
