### ISSUE TITLE
network.ESP32_SPI() parameters 'rst' and 'rdy' are unused

### ISSUE THREAD

**Issue by smuehlst** [sipeed/MaixPy-v1#214]
See the code in esp32_spi_config_io():

https://github.com/sipeed/MaixPy/blob/284ce83d6b6f6fe61e932cee439f4d0ec192028d/components/micropython/port/src/standard_lib/network/esp32/esp32_spi_io.c#L26

The `rst` and `rdy` parameters are passed in from the MaixPy `network.ESP32_SPI()` method, and they are not used for anything.

It is possible to pass `-1` to the `rst` parameter of `network.ESP32_SPI()`, but for the `rdy` parameter a valid GPIO pin must be provided.

It should be possible to pass `-1` to the `rdy` parameter in same manner as it is possible for the `rst` parameter.

**Comment by Neutree** [comment]
rdy is used, can not pass -1
