### ISSUE TITLE
LED defines in board info are incorrect for the MAiX Bit

### ISSUE THREAD

**Issue by anomaly256** [sipeed/MaixPy-v1#216]
Hi,

Minor issue, the defines for board_info.LED_G board_info.LED_B and board_info.LED_R are mixed up on the MAiX Bit.  LED_R points to the blue led, LED_G points to the red led, and LED_B points to the green led, at least on the v2.0 board using the v0.5.0 image (v0.5.0-22-g7ac6b09)

**Comment by Neutree** [comment]
the same as #266
