### ISSUE TITLE
CTRL-D crashes MaixPy

### ISSUE THREAD

**Issue by uhrheber** [sipeed/MaixPy-v1#22]
CTRL-D should do a soft reset of the board, and restart the code. Instead, I get the following report:

```
prower off
W (2100756768) SYSCALL: sys_exit called by core 0 with 0x0
```

And then the board hangs.

**Comment by wipping** [comment]
the new version of MaixPy supports soft-reset ,we will release it in the next time

**Comment by goatchurchprime** [comment]
Also, the CTRL-C doesn't work.  It doesn't stop loops

**Comment by robert-hh** [comment]
I have a patched code (main.c, uart_core.c and mpconfigport.h)  here, https://github.com/robert-hh/K210-Stuff, which does a soft reboot at Ctrl-D, and also break code at Ctrl-C, unless this is not wanted.

**Comment by Neutree** [comment]
fixed in new version , see releases page
