### ISSUE TITLE
camera : Sensor time out error

### ISSUE THREAD

**Issue by nitz08** [sipeed/MaixPy-v1#221]
In Arduino, I am getting "snap fail" in the serial monitor window. And black screen on LCD
For Maixpy IDE and Micropython, I am having the same issue.
If I modify the open-source python code (available on their website) to run only once (remove while loop), I am getting one picture on IDE and then error "Runtime Error: sensor timeout"

**Comment by marcoA152** [comment]
same here
got "Runtime Error: sensor timeout" also with helloworld.py... tried many different firmwares but works only for few frames then stop... maybe my camera sensor is faulty? maybe something overheating?
any help is appreciated!

**Comment by marcoA152** [comment]
> same here
> got "Runtime Error: sensor timeout" also with helloworld.py... tried many different firmwares but works only for few frames then stop... maybe my camera sensor is faulty? maybe something overheating?
> any help is appreciated!

a new OV2640 is arrived today, and yes, the problem is due to my old faulty sensor! now i can start again to play!
​thanks

**Comment by hktxt** [comment]
so, how to solve this? I encounter the same problem.

**Comment by nitz08** [comment]
I changed the sensor and which worked for me.
