### ISSUE TITLE
M1n板子接的gc0328摄像头，跑demo的时候由QVGA改为VGA格式视频是花的？

### ISSUE THREAD

**Issue by romix5417** [sipeed/MaixPy-v1#227]
![avatar](https://bbs.sipeed.com/2020-04-06/1586174289-548724-2020-04-06-195602.jpeg)

**Comment by gezp** [comment]
+1

**Comment by junhuanchen** [comment]
上图。

**Comment by Neutree** [comment]
可以尝试更新master分支的最新固件,有支持VGA

**Comment by junhuanchen** [comment]
是的，我也确认了，gc0328 存在 VGA 的配置，但它不工作，还不知道是什么原因呢

这个开发分支目前已经拉取了 master 分支更新，我想应该是摄像头的配置不当，要检查一下。

**Comment by TrekMax** [comment]
最新 develop 分支上已经修复了 GC0328 VGA 的支持。
