### ISSUE TITLE
The demo script doesn't work self_learning_classifier.py in the latest version of MaixPy

### ISSUE THREAD

**Issue by IagniukovMaksim** [sipeed/MaixPy-v1#238]
The demo script doesn’t work self_learning_classifier.py in the latest version of MaixPy the first time you take a photo everything freezes everything works fine on maixpy_v0.5.0_42_g458ed4e_minimum

**Comment by Neutree** [comment]
what output in terminal? if your model is right? I test just now with latest firmware, it's ok, reopen this if problem remain exist, thanks
