### ISSUE TITLE
System failure when using KPU and RX.record(tmp)

### ISSUE THREAD

**Issue by IagniukovMaksim** [sipeed/MaixPy-v1#239]
W (19517016825) SYSCALL: sys_exit called by core 0 with 0x1 when trying to read the microphone while any recognition example is running (MAIXDUINO + maixpy_v0.5.0_42_g458ed4e_minimum)

**Comment by valeumvale** [comment]
I've had the same problem, I can't send an image to the KPU while recording audio.

**Comment by junhuanchen** [comment]
- sipeed_conv_run kpu_run DMAC_CHANNEL5
- Maix_i2s_record i2s_receive_data_dma DMAC_CHANNEL5
Conflict, now fixed. 
Can reopen this issue if you still have questions.
