### ISSUE TITLE
Pre-built firmware on GitHub

### ISSUE THREAD

**Issue by DurandA** [sipeed/MaixPy-v1#24]
It would be nice to have pre-built images on the [relases page](https://github.com/sipeed/MaixPy/releases).

I am aware of the [firmware download link on bbs.lichee.pro](http://bbs.lichee.pro/d/170-maix-py-lichee-dan-sipeed-m1-mpy-bin) but this painful to use for non-chinese users.

**Comment by xiaoxiaohuixxh** [comment]
we will post the images before January 23.

**Comment by Novakov** [comment]
@xiaoxiaohuixxh Any update on this? I just received my Maix GO board and after uploading firmware.bin it's not booting - 'boot failed with exir code 233'

**Comment by Neutree** [comment]
of course we do, 

@Novakov  download method see [doc](https://maixpy.sipeed.com/en/get_started/upgrade_firmware.html), if you still have problem, create a new issue please
