### ISSUE TITLE
demo script SpeechRecognizer hangs

### ISSUE THREAD

**Issue by IagniukovMaksim** [sipeed/MaixPy-v1#241]
![image](https://user-images.githubusercontent.com/61647781/81337824-4d15aa80-90b4-11ea-94a9-df123dd8a7e2.png)

maixduino
MicroPython v0.5.0-62-gd6620f173

[MaixPy] i2s_num:0
<SpeechRecognizer>
Press the button to record the 1 keyword, the 1
...........---
modules_speech_recognizer_record

[MAIXPY]: record[0:0]
[MaixPy] speeking...

**Comment by easy-and-simple** [comment]
As minimum button push handling code cant work in this way

**Comment by easy-and-simple** [comment]
It crashes on record command
If record command is commented it runs cycle correctly 9 times but without any sense of course

**Comment by ghost** [comment]
I had a similar problem.
s.get_status() stays at 1 and doesn't change, so it's an infinite loop at line 95

**Comment by lancewj** [comment]
你好请问有没有遇到：ImportError: cannot import name SpeechRecognizer这个错误

**Comment by myuanz** [comment]
> 你好请问有没有遇到：ImportError: cannot import name SpeechRecognizer这个错误

默认固件没有开启这个功能, 现在需要自己编译固件.   
后面我们会在 lvgl 固件上默认开启这个功能.

**Comment by fengmin2611** [comment]
Hello,
I am also having the same problem. Is there anyone who can assist us?
Thank you

**Comment by myuanz** [comment]
> Hello,
> I am also having the same problem. Is there anyone who can assist us?
> Thank you

@Neutree

**Comment by junhuanchen** [comment]
use https://github.com/sipeed/MaixPy_scripts/tree/master/multimedia/speech_recognizer
