### ISSUE TITLE
06e16a3 breaks kmodel v4 support

### ISSUE THREAD

**Issue by AIWintermuteAI** [sipeed/MaixPy-v1#242]
Steps to reproduce the problem:
1) Download maixpy_v0.5.0_46_g06e16a3_minimum_with_ide_support.bin from https://cn.dl.sipeed.com/MAIX/MaixPy/release/master/maixpy_v0.5.0_46_g06e16a3 **OR compile it from source by doing git checkout 06e16a3 and then compiling with kmodelv4 support option enabled**
2) Upload Mobilenet(alpha=0.75) model (converted using nncase 0.2.0beta2) together with firmware
3) Run test script person_detector_v4fps.py
On loading model an error appears:
![2020-05-12](https://user-images.githubusercontent.com/32562299/81634188-0cfe5100-9441-11ea-8ed0-48408c2afc33.png)
[person_detector_v4fps.zip](https://github.com/sipeed/MaixPy/files/4613163/person_detector_v4fps.zip)
[v4beta2_13.29397_FPS_74.9ms.zip](https://github.com/sipeed/MaixPy/files/4613169/v4beta2_13.29397_FPS_74.9ms.zip)

**Comment by AIWintermuteAI** [comment]
https://github.com/AIWintermuteAI/aXeleRate/issues/5 and https://github.com/AIWintermuteAI/aXeleRate/issues/8 --- both the same problem

**Comment by corleonechensiyu** [comment]
@AIWintermuteAI i have the same error when i use the maixpy_v0.5.0_46* even the latest version .But version maixpy_v0.5.0_31_gd3e71c0 can pass.

**Comment by AIWintermuteAI** [comment]
Yes, correct. I know versions before v0.5.0_46 can be used normally :) I just want to let sipeed team know that v0.5.0_46 causes issue, that they need to solve.

**Comment by AIWintermuteAI** [comment]
Kmodel v4 (converted with nncase beta2) can be used normally in https://github.com/sipeed/MaixPy/commit/461f841fe95cf9109df32e1f3a76d60a659c31af 
Issue closed, good job @Neutree

**Comment by BlackEyesCoder** [comment]
How can I do "Upload Mobilenet(alpha=0.75) model (converted using nncase 0.2.0beta2) together with firmware" in https://www.instructables.com/id/Object-Detection-With-Sipeed-MaiX-BoardsKendryte-K/. thanks

**Comment by AIWintermuteAI** [comment]
Use https://github.com/sipeed/kflash_gui tool, choose firmware file(flash it to 0x00000) and model file(flash to 0x200000 for example), then flash.
