### ISSUE TITLE
Question about sending data from MaixPy to PC through usb 

### ISSUE THREAD

**Issue by zzzeddy** [sipeed/MaixPy-v1#244]
I want to make my MaixPy BIT to keep sending some data to PC which was connected using /dev/ttyUSB* with some interval.
In addition, Is it possible to make connection from MaixPy BIT to PC using micropython?

Thanks in advance!

**Comment by easy-and-simple** [comment]
Investigate how works uPyLoader

**Comment by Neutree** [comment]
and for easy usage, you just need send data to PC, just need use [machine.UART](https://cn.maixpy.sipeed.com/en/libs/machine/uart.html) module, call `write` function to send data  to PC

I close this issue, if you remain hve problem, reopen it
