### ISSUE TITLE
ModuleNotFoundError: No module named 'serial'

### ISSUE THREAD

**Issue by easy-and-simple** [sipeed/MaixPy-v1#251]
Why I get error when Try to compile maixpy from source?

maixpy
Traceback (most recent call last):
  File "project.py", line 31, in <module>
    exec(f.read())
  File "<string>", line 37, in <module>
  File "/home/user1/maixpy/MaixPy/tools/flash/flash.py", line 12, in <module>
    import serial.tools.miniterm
ModuleNotFoundError: No module named 'serial'

**Comment by easy-and-simple** [comment]
How to build documentation is bad and misleading and cant be follower step by step because some steal are missed, and should improvise

**Comment by GuilhermeAgostin** [comment]
I have the same problem, can you help me solve it?

![Captura de Tela (289)](https://user-images.githubusercontent.com/59300376/86071777-7d474d00-ba56-11ea-8cb4-3f4b42018a65.png)

**Comment by easy-and-simple** [comment]
sudo pip3 install -r requirements.txt

or 

sudo pip install pyserial==3.4
