### ISSUE TITLE
Latest NES emulator display X/Y swap and display at wrong position.

### ISSUE THREAD

**Issue by galaxystar1yuji** [sipeed/MaixPy-v1#252]
I use Maix Bit, and play "mario.nes".
NES emulator of maixpy_v0.5.0_52 is no problem.
But NES emulator of maixpy_v0.5.0_63 display X/Y swap. And some characters display at wrong position. So I cannot play game.
I think that you had better restore to the old codes of nes.

**Comment by TrekMax** [comment]
The old other configuration has been restored
Separate the LCD configuration from  NES config later
