### ISSUE TITLE
Memory problem with maixpy 5 and loaded 3 face models

### ISSUE THREAD

**Issue by minyatos** [sipeed/MaixPy-v1#253]
I have RAM problem with new versiyon of maixpy_v0.5.0_63_g2d307ae.bin & FD_,FE_ and KP_ face models. 
They can not work together on Maix Go. But I also need both face recognation and QRcode.
If I load a much older versiyon maixpy I can load all 3 models but then  find_qrcodes ,find_blob functions won't work.

**Comment by easy-and-simple** [comment]
did you tried minimum firmware? If yes then Init and deinit them one by one so only 1 of the to be active at same time

**Comment by minyatos** [comment]
Yes, i will try to deinit them as you said, i will inform you about process thank you

**Comment by minyatos** [comment]
![image](https://user-images.githubusercontent.com/60696483/83340587-c33bb480-a2e2-11ea-9d76-1a1d73c6e66e.png)
Hi again, i tried kpu.deinit(task) function and it didn't work somehow cause I'm using your 3 model face recognition and getting images from camera. (https://github.com/sipeed/MaixPy_scripts/blob/master/machine_vision/demo_face_recognition.py)
Then I tried kpu_loadflash function, it didn't work either when I convert the 3 models with convert.py function you provided. Since I couldn't see inside the models, I can't say what is wrong.  
Then I tried to compile my own maixpy with my own requirements, and include qrcode functionality, but it din't work with face model project. I though maybe I missed to include something and add lib_sipeed_kpu option and it gets error at the following code block I attached.
![image](https://user-images.githubusercontent.com/60696483/83341495-d6ec1880-a2ec-11ea-8bfb-c723ce0965f1.png)
I think the main problem is at kpu.forward function. Before this line of code; 
###free gc heap memory : 126 KB
###free sys heap memory: 1000 KB
So can you please help me with;
1-  how can I compile maixpy_minimum version with qrcode functionality and also support the demo_face_recognition example? What is the dependencies, that my compiled version won't work at face demo sample(but work at qrcode, I managed that)?
2- If it needs compile of lib_sipeed_kpu, can you please correct micropython requirements code for me to compile. (lib_sipeed_kpu.a ?)  
3- why I can not convert FD,FE and KP face models for load from flash functionality and couldn't run them? Is it about models, if yes what is the correct face models for me to use flash functionality? Can you provide these models?
Thank you :)

**Comment by easy-and-simple** [comment]
I have no idea what are you doing and what is causing your problem but can advice you what you could try if this is low memory problem
Try this, save script to board as boot.py disconnect from ide and reboot board via reset key
Also when you compile your firmware version most important is to uncheck double buffering option

**Comment by minyatos** [comment]
Can you provide working "convert.py" function for the below face models?
I want to use _kpu.load_flash(0x400000, 0, 0,50000000)_

![image](https://user-images.githubusercontent.com/60696483/83385234-89a59f00-a3f1-11ea-8f0b-f4fd0efc521a.png)
