### ISSUE TITLE
OSError: [Errno 5] EIO b7f0c13

### ISSUE THREAD

**Issue by corleonechensiyu** [sipeed/MaixPy-v1#255]
![1590668780(1)](https://user-images.githubusercontent.com/39826330/83141136-ba4fb500-a121-11ea-8602-88777b109517.png)

**Comment by easy-and-simple** [comment]
probably your image is too big so you should make it smaller in size or use copy_to_fb=True option as second parameter in constructor

**Comment by corleonechensiyu** [comment]
@easy-and-simple With the latest firmware, the firmware used a month ago is no problem, regardless of the size of the picture.
