### ISSUE TITLE
Image font unacceptable small and useless

### ISSUE THREAD

**Issue by easy-and-simple** [sipeed/MaixPy-v1#258]
Image font is unacceptable small and useless
Fake 8x10 pixels
Real 4x6 pixels WTF?! Realy useless. Nothing can't be written in 1x scale and 2x scale looks really ugly. Words describing look of higher scales are not suitable for kids
It should be at least 2x that means atleast 8x12 real pixels and should be unified in size with size of LCD font

**Comment by Neutree** [comment]
we have update the font in develop branch @junhuanchen

**Comment by junhuanchen** [comment]
Now

The Image.font change 8 * 12

![image](https://user-images.githubusercontent.com/32978053/89005051-20c99d00-d336-11ea-84df-0026f305bb3d.png)

![image](https://user-images.githubusercontent.com/32978053/89005048-1d361600-d336-11ea-90f0-b671d5814e49.png)

Maybe you can try the latest.

**Comment by easy-and-simple** [comment]
Is it already working?
If yes why then these changes are only in development branch?
When changes will be available in master branch?

**Comment by junhuanchen** [comment]
> Is it already working?
> If yes why then these changes are only in development branch?
> When changes will be available in master branch?

1. Need to fine tune the font effects.

2. Includes getting word libraries from Flash/SD.

**Comment by easy-and-simple** [comment]
OK thank you for this information!
Will wait update of master branch

**Comment by junhuanchen** [comment]
> OK thank you for this information!
> Will wait update of master branch

Merge branch 'master' of https://github.com/sipeed/MaixPy into develop

https://github.com/sipeed/MaixPy/commit/8158d48704c0225790bc03dcc1affc259b364736

If you have other problems, you can reopen it.
