### ISSUE TITLE
why pix_to_ai still return none?

### ISSUE THREAD

**Issue by lastrei** [sipeed/MaixPy-v1#264]
import sensor, lcd, image
import KPU as kpu

print("init")
lcd.init(freq=15000000)
print("init ok")
x = image.Image('/sd/2.jpg',copy_to_fb=1)
lcd.display(x)
print(x)
print(x.pix_to_ai())
del x
===========================================

init ok
{"w":320, "h":240, "type"="rgb565", "size":153600}
None

i want to run yolo2 from SD card image
and i found 
[MAIXPY]kpu: pix_ai is NULL!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: [MAIXPY]kpu: check img format err!

so i see this 
https://github.com/sipeed/MaixPy/issues/110

it' s told me to use img.pix_to_ai()
but the pix_to_ai still return None
why??

**Comment by Neutree** [comment]
image.pix_to_ai() always returen None, what it do is transport pixels to kpu input memory area, so if you called some image operations like `image.resize()` `image.copy()` etc. , these operation complete in image memory, but kpu's input memory not changed, so if we want to run kpu after these operations we have to call this func to update kpu's input, or we don't need to call this func( e.g. we don't use kpu, just display by lcd, we don't need to call `image.pix_to_ai`)

for transport from image memory to kpu's input memory need cost time, so we didn't do it in every image operation function, we call image.pix_to_ai() manually instead
