### ISSUE TITLE
board_info.pin_map didn't match led pin on Maix Bit

### ISSUE THREAD

**Issue by ZRandomize** [sipeed/MaixPy-v1#266]
LED_R=14,LED_G=13,LED_B=12
in fact,it should be LED_R=13,LED_G=12,LED_B=14

**Comment by Neutree** [comment]
There's several boards, they have defferent pin difinition, so maybe the LED pins not correct for bit, but we are adding board config to maixpy, it will be resolved. The develop branch has did it
