### ISSUE TITLE
kpu load error -3

### ISSUE THREAD

**Issue by pritamghanghas** [sipeed/MaixPy-v1#268]
While we try to load model, we get kpu error. From The MaixPy sources, I couddn't find what -3 means, there all enums are +ve.

task = kpu.load('/sd/model.kmodel')
ValueError: [MAIXPY]kpu: load error -3 from this line

model can be accessed at this location https://drive.google.com/file/d/1qorFP6I7mo5T_cVk3XzfeY2XULG9LGah/view?usp=sharing

**Comment by myuanz** [comment]
Plz tell us the Maix firmware version.

**Comment by pritamghanghas** [comment]
It gave -3 error on maixpy_v0.5.0_95_g05c4e70_with_lvgl.bin. Later I loaded the firmware attached in this blog post https://en.bbs.sipeed.com/t/topic/1790, I think it was first firmware that supports v4. In this firmware the model loaded but the call to kpu.forward() hangs up and nothing happens. The only way to recover seems to be to reset the board. I don't know how to work around this problem.

**Comment by myuanz** [comment]
Thanks for your feedback, this issue has been added to our todo list. 😅

**Comment by pritamghanghas** [comment]
Let me know if tflite model is also need for any verification, I can upload that as well.

**Comment by myuanz** [comment]
No, you can convert any model supported by nncase.

**Comment by Neutree** [comment]
@pritamghanghas Now you should customsize your firmware according the build.md, or generate a firmware by online compile tool(https://www.maixhub.com/compile.html), make sure kmodel v4 support is checked

I tried your kmodel, it's ok
![image](https://user-images.githubusercontent.com/8625829/88901538-7f820e80-d283-11ea-989b-3023b572298e.png)

If there remains error, reopen this issue
