### ISSUE TITLE
FFT not working

### ISSUE THREAD

**Issue by valeumvale** [sipeed/MaixPy-v1#269]
I was on using the fft demo on v0.3.2, but then I wanted to try the speechRecognition demo and it didn't work because there is no  speechRecognition file on 'modules', so i updated the firmware to v0.5.0_95_g05c4e70, which still didn't work and now the FFT demo that I was using on a script always returns 0 on the new firmware, and on the old the "force=true" used on fm.register() comands return as an error.
Can someone help me?

![image](https://user-images.githubusercontent.com/67641994/86135203-664e3c80-bae2-11ea-8553-477b76fde695.png)

**Comment by valeumvale** [comment]
Im using maispy dock and the script works on v0.3.2 if i remove the "force=true", but after I send it to the board as boot.py it doesn't run automaticly outside of Maix IDE

![image](https://user-images.githubusercontent.com/67641994/86135490-c93fd380-bae2-11ea-90e0-3cebd633756a.png)

**Comment by myuanz** [comment]
Have a try about [0.5.0](https://dl.sipeed.com/MAIX/MaixPy/release/master)? May be a solved problem

**Comment by valeumvale** [comment]
Problem solved.
I was using the latest 0.5.0, but I had comented "lcd.display(img)" because I didn't need the display but it looks like I can´t, I'll be changing be code so it doesn´t need a display.
