### ISSUE TITLE
ussl library is not included in master

### ISSUE THREAD

**Issue by valenzmanu** [sipeed/MaixPy-v1#281]
This issue comes from https://github.com/sipeed/MaixPy/issues/105

Hello @junhuanchen, I tried today the last version in master but it does not include ussl:

```
>>> help('modules')
help('modules')
KPU               hashlib           pye_mp            uio
Maix              heapq             random            ujson
__main__          image             re                ulab
_boot             json              sensor            uos
_thread           lcd               socket            urandom
_webrepl          lodepng           struct            ure
array             lvgl              sys               usocket
audio             lvgl_helper       time              ustruct
binascii          machine           touchscreen       utime
board             math              ubinascii         utimeq
builtins          math              ucollections      uzlib
cmath             micropython       ucryptolib        video
collections       modules           uctypes           zlib
errno             nes               uerrno
fpioa_manager     network           uhashlib
gc                os                uheapq
Plus any modules on the filesystem
```

After that, I tried using the version in https://github.com/sipeed/MaixPy/tree/develop (which does have ussl) but the camera is not working. I'm using a Maixduino.

**Comment by junhuanchen** [comment]
but the camera is not working. why ?

**Comment by valenzmanu** [comment]
I'm sorry I wasn't clear in my previous comment. 

Here are 2 pictures of my project using [this version of MaixPy](https://dl.sipeed.com/MAIX/MaixPy/release/master/maixpy_v0.5.0_98_g7ec09ea):
![image](https://user-images.githubusercontent.com/21220618/88333131-e97f3e80-ccec-11ea-9be5-ed1f61c97c68.png)
![image](https://user-images.githubusercontent.com/21220618/88333140-ee43f280-ccec-11ea-9db7-57af54f49964.png)

And here is the exact same code using the [develop branch](https://github.com/sipeed/MaixPy/tree/develop):
![image](https://user-images.githubusercontent.com/21220618/88333349-52ff4d00-cced-11ea-9a62-9abfb23aa3c2.png)
![image](https://user-images.githubusercontent.com/21220618/88333362-57c40100-cced-11ea-895a-29ea1d94d3b7.png)

**Comment by valenzmanu** [comment]
I'm not sure how or where to debug what happened since the only thing I changed was the MaixPy version.

**Comment by junhuanchen** [comment]
set sensor rgb565 color change to yuv422

**Comment by valenzmanu** [comment]
Thanks, it worked.
