### ISSUE TITLE
KMODEL V4 can't be loaded MAIXPY frezes without error

### ISSUE THREAD

**Issue by easy-and-simple** [sipeed/MaixPy-v1#282]
tflite model converted succesfuly to kmodel v4 by nncase 0.2 beta 4 makes MAIXPY latest build with enables V4 support to freeze on try to load model without displaying any error
Same model converted to KMODEL V3 is working

**Comment by Neutree** [comment]
try latest code, compile your own firmware here : https://www.maixhub.com/compile.html , check kmodel V4 support

**Comment by Neutree** [comment]
nncase2.0 beta4 is not supported, you can use beta2

**Comment by Neutree** [comment]
same as #256
