### ISSUE TITLE
Feature request: support for UXGA JPEG saving, add AVI frame, base resolution for windowing

### ISSUE THREAD

**Issue by easy-and-simple** [sipeed/MaixPy-v1#285]
Hello Guys,
Would you add UXGA support as base resolution for windowing mode, and also for taking JPEG images that then to be saved as JPEG image file or added as frames in AVI? 
OV2640 can make JPEG images so main problem here is ability to switch OV2640 between compressed JPEG mode and uncompressed RGB mode

**Comment by junhuanchen** [comment]
I don't know the implementation details, but it might work.

Can you describe the process of implementation？

**Comment by easy-and-simple** [comment]
UXGA is intentionally restricted by MAIXPY source code and JPEG image sensor option is not supported.
Also windowing mode  is not working if base resolution is set to values over 640x480 no matter that window is set to 320x240 and required RAM buffer is for image size 320x240 and it doesn't depend on base resolution
If image resolution is limited by MAIXPY source code it is not possible to take pictures in UXGA resolution and store them as JPEG image files or add them as frames in AVI video recording
Example usage is setting image sensor to 320x240 RGB mode running yolo object recognition or face recognition and at given condition switch image sensor to JPEG mode and UXGA resolution and taking picture in good resolution that is saved as JPEG image or UXGA video frame for security surveillance scenario. Then sensor is switched back to 320x240 RGB mode and object detection/face detection continue to next predefined event and so on. Here sensor mode switching should be implemented without issues.
Other example usage is setting UXGA base resolution(that is default for OV2640 sensor) and 320x240 windowing mode for implementing 4x digital zoom and precise area scanning without loss for object detection needs. Here sensor switching between JPEG and RGB mode is not required

**Comment by Neutree** [comment]
* SXVGA support is a feature request, it's no implement now, same as #243 
* K210 can not use JPEG mode of sensor, for hardware limitation, just can use RGB565 or YUV mode

**Comment by AhmadPanogari** [comment]
Any update for this Issue?

I also need that image size when taking pictures 

and is the OV5640 already supported?

**Comment by ZoneMR** [comment]
> * K210 can not use JPEG mode of sensor, for hardware limitation, just can use RGB565 or YUV mode

What is the specific hardware limitation which would prevent using the JPEG output from the OV2640?
