### ISSUE TITLE
sys.stdin.read() does not work as expected

### ISSUE THREAD

**Issue by robert-hh** [sipeed/MaixPy-v1#29]
sys.stdin.read(1) should return one char from the console when a key is pushed. Instead it returns a null-byte immediately. Similar, sys.stdin.read(n) returns a string of n null-bytes. This affects all related functions like sys.stdin.readline(), sys.stdin.readlines(), sys.stdin.readint() too.
input() also fails.

**Comment by robert-hh** [comment]
The following change of the function mp_hal_stdin_rx_chr() in uart_core.c fixed this bug/omission:
```
// Receive single character
int mp_hal_stdin_rx_chr(void) {
    unsigned char c = 0;
    for (;;) {
        int cnt;
        cnt = read_ringbuff(&c,1);
        if (cnt > 0) {
            break;
        }
        MICROPY_EVENT_POLL_HOOK
    }
    return c;
}
```
MICROPY_EVENT_POLL_HOOK is preliminary defined in mpconfigport.h as:
```
#define MICROPY_EVENT_POLL_HOOK \
    do { \
        extern void mp_handle_pending(void); \
        mp_handle_pending(); \
    } while (0);
```
With that change, the editor pye can be adapted to work. At least I have a working version now.

**Comment by robert-hh** [comment]
I have some patches here https://github.com/robert-hh/K210-Stuff, file uart_core.c and mpconfigport.h, which fixes that.

**Comment by Neutree** [comment]
thanks, fixed in latest version ~~~
