### ISSUE TITLE
saving image to PC

### ISSUE THREAD

**Issue by ChahidTALHA** [sipeed/MaixPy-v1#291]
I am using Maixduino board for my project, and the latest version of Maixpy IDE to develop my code. I am looking for a specific python script that would help me save images taken by the camera (OV2640) into my PC directory.
There is a way to do it by right clicking the frame buffer then save the image to a path. I want to automate this task for my project but I don't know how.
Thanks in advance.

**Comment by Neutree** [comment]
image.save()

https://maixpy.sipeed.com/en/libs/machine_vision/image.html#imagesavepath-roi-quality50

**Comment by ChahidTALHA** [comment]
image.save() allows me to save the image to maixduino's flash. is there a code that would allow me to save the image directly to my  machine (Windows 10)

**Comment by Neutree** [comment]
use upyloader https://github.com/BetaRavener/uPyLoader/releases
