### ISSUE TITLE
Maixduino compatible cameras

### ISSUE THREAD

**Issue by ChahidTALHA** [sipeed/MaixPy-v1#297]
Hi everyone, 
I am using a Maixduino board for my project and I would like to know all the cameras references that are compatible with this board, I got the OV2640 but i am looking for a better quality one.
Do these references work with the maixduino board:
+OV7740
+OV5640
Pleased to suggest a list of the compatible cameras with the Maixduino board.
Thanks in advance

**Comment by Neutree** [comment]
OV7740 GC0328 are supported

**Comment by junhuanchen** [comment]
The current firmware supports OV2640, GC0328, OV7740, GC2145, OV5640.

**Comment by junhuanchen** [comment]
If you have other problems, you can reopen it
