### ISSUE TITLE
What functions are available while using the minimum firmware ?

### ISSUE THREAD

**Issue by staberas** [sipeed/MaixPy-v1#301]
What functions are available for the image & Kpu while on the minimum firmware ? 
Im trying to find information and i cant find anything... Im currently trying to see my options since i need the face recognition model and find_similarity ,  find_blobs , QR and _thread for my project. Thanks

**Comment by Neutree** [comment]
just use the normal firmware, minimum no these function, and you can customize your firmware here: 
https://www.maixhub.com/compile.html

**Comment by AIWintermuteAI** [comment]
Just to expand on the answer - if you build the firmware manually and open the config file for minimum firmware you will see this:
![Screenshot from 2020-08-26 13-50-54](https://user-images.githubusercontent.com/32562299/91264931-55007400-e7a3-11ea-8254-272b898eda17.png)
So, find blobs, QR and thread are not available in minimum firmware.

**Comment by staberas** [comment]
Thanks, but i have used the custom firmware creator  ( min omv & _thread )  but my code still crashes [dew to memory ]. Anyway to make my question more clear is , which functions min omv  has available to use?

**Comment by Neutree** [comment]
basic image ops like `draw_...` `copy` etc. but no algrightm like `find_...`

**Comment by staberas** [comment]
Found it:  booting the maix without an sd into REPL and then typing ` >>>help(image.Image())` 
or  `>>>help(kpu) ` etc and it will give a list of functions that are available.
