### ISSUE TITLE
Firmware v0.5.0_200 & v0.5.0_202	have image viewing problem

### ISSUE THREAD

**Issue by staberas** [sipeed/MaixPy-v1#304]
Just flashed maixpy_v0.5.0_200_g8f6aa7b & maixpy_v0.5.0_202 (minimum both) and while they solve some problems i had the jpg & bmp images that are displayed with incorrect coloring... and im also think there is a scaling issue

**Comment by staberas** [comment]
![IMG_2020](https://user-images.githubusercontent.com/2744235/91831420-b6658e80-ec4c-11ea-899b-95a84e688e23.jpg)
there is also extra space on the top and bottom

**Comment by junhuanchen** [comment]
Maybe you could test tft_fill_data to determine how much the size of its entire area is different.

https://github.com/sipeed/MaixPy/blob/e1ebb56db6457b1a4da072ed5cba44e22b6be06a/components/drivers/lcd/src/st7789.c#L133

Check the situation.

**Comment by staberas** [comment]
did lcd.clear((255,206,0)) and its filling it with yellow color 
note the pictures are 320x228 and previous firmwares worked fine. I can see the latest firmware has applied some rescaling since now the text now is way less blocky that the previous versions

**Comment by junhuanchen** [comment]
There was an overflow of the previously filled address, so this problem was not found.

In particular, there are undefined bugs in the area of rotation.

**Comment by junhuanchen** [comment]
Can you see this https://github.com/sipeed/MaixPy/commits/master/components/drivers/lcd/src/lcd.c

It is best if the cause of the problem is identified before and after

**Comment by junhuanchen** [comment]
Maybe you can show 320 * 240 for comparison

**Comment by staberas** [comment]
Ok, this is interesting i initialised the lcd way after i did other stuff (like loading the models, init servo etc ) it seems now that i moved the init of lcd at the start the color and scaling problem has vanished ... 

maybe it has to do with memory management?

**Comment by junhuanchen** [comment]
Previously, the starting address in py_lcd.c was not initialized, which caused a lot of strange phenomena. If there are similar situations, you can attach the code + picture and reopen the issue.
THX ~
