### ISSUE TITLE
OSError: Reset Failed( sensor.reset() )

### ISSUE THREAD

**Issue by agenthong** [sipeed/MaixPy-v1#308]
first time use maixpy, why does it happen?
![image](https://user-images.githubusercontent.com/59220627/93178595-096c3500-f767-11ea-937b-2e8ad75eaffc.png)

does the camera get sth wrong?

**Comment by agenthong** [comment]
I‘ve tried old or latest firmware, but it still can't work. I'm wondering if it because the camera is broken.

**Comment by junhuanchen** [comment]
Your camera is not plugged in
