### ISSUE TITLE
Camera not reading QRCODE

### ISSUE THREAD

**Issue by deby13** [sipeed/MaixPy-v1#314]
camera is working but QRcode is not been interpreted

**Comment by Neutree** [comment]
try to set hmirror for sensor by:
```python
sensor.set_hmirror(1)
```

**Comment by Neutree** [comment]
https://github.com/sipeed/MaixPy_scripts/blob/master/machine_vision/demo_scan_qr_code.py

**Comment by deby13** [comment]
Thanks a lot, that solved the problem.
