### ISSUE TITLE
Colors inverting after any FW download

### ISSUE THREAD

**Issue by Kabron287** [sipeed/MaixPy-v1#321]
Board MaixCube with v0.5.0-95-g05c4e70 out of the box.

if I download the same FW maixpy_v0.5.0_95_g05c4e70.bin or any newvest e.g. maixpy_v0.5.1_103_gf9bb0bb.bin,
I got inverted colors.
And this is not the first case. I got similar results with other boards.
Fortunatelly, now I did it to RAM, instead of flash.

What could be done?

**Comment by junhuanchen** [comment]
see this https://github.com/sipeed/MaixPy_scripts/tree/master/board

**Comment by Kabron287** [comment]
> see this https://github.com/sipeed/MaixPy_scripts/tree/master/board

Thanks a lot. It's important update.

**Comment by Kabron287** [comment]
After upgrade to v0.6.2_12 colors returned to **inverted** state. **config_maix_cube.py** does not helps.

**Comment by Kabron287** [comment]
It was due wrong example code here:
https://maixpy.sipeed.com/zh/develop_kit_board/maix_cube.html#
