### ISSUE TITLE
Maix Bit （with mic）cannot load smodel file in sdcard

### ISSUE THREAD

**Issue by YanxingLiu** [sipeed/MaixPy-v1#323]
I want to read 3 smodel files in sdcard ,  But it doesn't work. And it report a Value Error.
![6FU556AOLTQ_GF%9CPYB$3T](https://user-images.githubusercontent.com/42299757/95646424-03b20700-0afb-11eb-96c2-dda7a2168702.png)
I can read smodel files in flash,So I wonder if the smodel files can be read in sdcard.
The codes:
![PYBO{144T72~EIFT}OD4VC1](https://user-images.githubusercontent.com/42299757/95646456-4bd12980-0afb-11eb-8833-1bd4991b4aff.png)
 The firmware is the newest 0.5.1 minimum with ide.
Thanks!

**Comment by Neutree** [comment]
https://github.com/sipeed/MaixPy/blob/22ab99ea284a63394f6e1123e90af6cb7d4c2ea6/components/micropython/port/src/Maix/Maix_kpu.c#L398-L412

you should not change filename's extension, it should be like `*.smodel`
