### ISSUE TITLE
Is it open source? I mean functions packed into libraries.

### ISSUE THREAD

**Issue by longtolik** [sipeed/MaixPy-v1#331]
I work with bare metal. Trying to port feature map from MaixPy to C/C++.
In MaixPy we have next for instance: a=kpu.set_layers(task, 1) and then fmap=kpu.forward(task,img2)
but "set_layers" links to _sipeed_kpu_model_set_output()._ And last is not open sourced as it's packed in library file (.a)
So, I'd like to know is it possible to get the feature map in C and bare metal?
Thanks!

**Comment by junhuanchen** [comment]
This section is not open source, but it is not mysterious, so you can either use the NNCase interface directly or call the (.a) directly as a function.
