### ISSUE TITLE
Amigo LVGL Touchscreen Support?

### ISSUE THREAD

**Issue by brotherdust** [sipeed/MaixPy-v1#350]
Hello!
When is LVGL touchscreen support planned for the Amigo?

None of the provided examples work with Amigo, presumably because MaixPy lacks support for FT6X36.

Please advise.

**Comment by junhuanchen** [comment]
well... you can use this https://github.com/sipeed/MaixUI/blob/master/driver/touch.py

**Comment by brotherdust** [comment]
Once again, thank you!
