### ISSUE TITLE
Couldn't compile k210-freertos: -latomic

### ISSUE THREAD

**Issue by GitJer** [sipeed/MaixPy-v1#36]
I couldn't compile the port for k210-freertos because the compiler couldn't find '-latomic'. After some web searches it appears that this library isn't explicitly needed. Thus in the file MaixPy/ports/k210-freertos/k210.mk the reference to atomic can be removed. Then it compiles.

**Comment by Neutree** [comment]
Which version of toolchain you used? v7.2 or v8.2?

you must use V8.2 to compile the MaixPy code, [download here](https://kendryte.com/downloads/)

**Comment by GitJer** [comment]
You are right.
Although I did notice that file I downloaded has '.tar.gz' at the end, while it is actually just a '.tar'

Thanks.
