### ISSUE TITLE
The maixpy_v0.6.2_6_gd78d036a2_m5stickv.bin version does not have ws2812 support.

### ISSUE THREAD

**Issue by fraramon** [sipeed/MaixPy-v1#373]
Hi I have a UnitV device from m5stack and I am using the release maixpy_v0.6.2_6_gd78d036a2_m5stickv.bin and I have observed that it does not have support for ws2812. What I can do? Thanks for all the help you can give me.

**Comment by Neutree** [comment]
for m5stickv, now  you have to compile it, and select ws2812 support in menuconfig, see https://github.com/sipeed/MaixPy/blob/master/build.md or just use online compile tool at https://www.maixhub.com/compile.html

**Comment by fraramon** [comment]
Ok, thanks for everything.
