### ISSUE TITLE
config_maix_duino.py wrong pin assignment on PIN7 and missing analog pins

### ISSUE THREAD

**Issue by myuunosuke** [sipeed/MaixPy-v1#374]
I just noticed that the PIN7 of Maixduino configuration has wrong value assigned.
https://github.com/sipeed/MaixPy_scripts/blob/master/board/config_maix_duino.py

Currently:
`'PIN7':16,`

Correct pin assignment is 15
`'PIN7':15,`

And I don't see any pin configuration for the analog pins (A0 - A5)..., how should I access those pins?

Thank you,

**Comment by junhuanchen** [comment]
esp32 adc need use https://github.com/sipeed/MaixPy_scripts/blob/master/network/demo_esp32_read_adc.py

**Comment by myuunosuke** [comment]
Thank you.
