### ISSUE TITLE
Maix Cube Drivers

### ISSUE THREAD

**Issue by diazGT94** [sipeed/MaixPy-v1#376]
I have a Maix Cube that I want to use for a custom project. However, my laptop doesn't recognize the serial COM port I've tried installing the same drivers for the M1 board, but still, it doesn't recognize it.

**Comment by junhuanchen** [comment]
It looks like there's something wrong with the drive.

**Comment by junhuanchen** [comment]
Please provide more information or the issue will be closed soon

**Comment by diazGT94** [comment]
I didn't succeed so I replace it with the Maixduino and everything worked.
