### ISSUE TITLE
maixpy_k210 custom build problem

### ISSUE THREAD

**Issue by HaticeGozdeTorun** [sipeed/MaixPy-v1#377]
I add htpa support from menu and compile with success.
After loaded on board, 

board_info didn't work
fpioa_manager didn't work

fm.register(board_info.LED_B, fm.fpioa.GPIO0)

AttributeError: type object 'board_info' has no attribute 'LED_B'

**Comment by Neutree** [comment]
@junhuanchen

**Comment by junhuanchen** [comment]
see this https://github.com/sipeed/MaixPy/issues/378.
