### ISSUE TITLE
v0.6.2-15-g0118a9a77 kpu: load error:2002, ERR_KMODEL_VERSION: only support kmodel V3

### ISSUE THREAD

**Issue by zhaoshenhao** [sipeed/MaixPy-v1#379]
I got issue with latest bin.
kpu: load error:2002, ERR_KMODEL_VERSION: only support kmodel V3

What I have done below:

    Loaded latest bin:
    MicroPython v0.6.2-15-g0118a9a77 on 2021-01-12; Sipeed_M1 with kendryte-k210

    Modified the code:
    if name == "main":
    try:
    main(model_addr="/sd/face_find.kmodel", lcd_rotation=0, sensor_hmirror=False, sensor_vflip=False)
    #main( model_addr=0x300000, lcd_rotation=0, sensor_hmirror=False, sensor_vflip=False)

    Downloaded the model from https://dl.sipeed.com/MAIX/MaixPy/model

    Upload to sd card and renamed to find_face.kmodel

            os.listdir('/sd')
            ['main.py', 'face_model_be_at_0x600000.kfpkg', 'mnist.kmodel', 'mobilenet_0x300000.kfpkg', 'face_find.kmodel']

Error:
init i2c2

[MAIXPY]: sensor id = 9d
[MAIXPY]: find gc0328
/sd/face_find.kmodel
Traceback (most recent call last):
File "", line 55, in
File "", line 50, in main
File "", line 47, in main
File "", line 47, in main
File "", line 34, in main
ValueError: [MAIXPY]kpu: load error:2002, ERR_KMODEL_VERSION: only support kmodel V3
kpu_net del

Please advise.

**Comment by Neutree** [comment]
replied in your another issue, you used the wrong model
