### ISSUE TITLE
有关board_info的问题

### ISSUE THREAD

**Issue by ryrobotics** [sipeed/MaixPy-v1#38]
逐条语句进行输入的时候board_info.可以正常使用，但是在文件中使用就会出现NameError: name 'board_info' isn't defined，代码参考PWM的例程1

**Comment by Neutree** [comment]
这个类是在 `_boot.py`文件里面导入的，可以自己导入,类似的 `fm`对象也是
```python
from board import board_info
from fpioa_manager import *
```

**Comment by Ray0117** [comment]
谢谢！我还遇到一个问题就是运行完一个py文件后再运行其他的就没有输出和反应了，不知道是和什么原因有关。
![yty7 2e455 8r m3t 8](https://user-images.githubusercontent.com/32253721/53472409-71cec500-3aa2-11e9-9960-4b83ebff3a70.png)

**Comment by ryrobotics** [comment]
谢谢，导入board_info解决了一部分的问题 ，但是还是会提示`AttributeError: type object 'board_info' has no attribute 'LED_G'`。
另外文档中提到的运行文件方式是通过import实现的，但是这样在运行一次之后就必须要reset才能继续使用不然就没有结果，请问有没有好的解决方法。

**Comment by wipping** [comment]
请参考_boot.py的用法，导入board_info的是个类，需要开辟对象才能用
```
from board import board_info
board_test = board()
board_test.LED_G
```
