### ISSUE TITLE
有没有添加opencv支持的计划

### ISSUE THREAD

**Issue by zhaoshenhao** [sipeed/MaixPy-v1#381]
尝试了所有和图像视频有关的各种代码，非常感谢sipeed为大家提供了一款非常出色的产品。

使用中发现一些限制。由于目前KPU支持的算法和调优非常有限，如果能有openCV的支持，做些预处理，或者直接使用OpenCV的一些算法，那么作为开发人员，我们的可以利用这块板子做更多的工作。

请问一下，是否有添加OpenCV的计划。我查看了OpenCV网站，有人在尝试 risc-v 的移植工作。如果有的话，大概啥时候出。

谢谢。

**Comment by Neutree** [comment]
无
