### ISSUE TITLE
MaixPy compile failed.

### ISSUE THREAD

**Issue by willendzw** [sipeed/MaixPy-v1#391]
Hi

I used latest code of MaxiPy to build. But it failed, error refer to below:

Scanning dependencies of target gen_collected_h
usage: /home/willen/Documents/MaixPy/components/micropython/core/py/makeqstrdefs.py command mode input_filename output_dir output_file
micropython/CMakeFiles/gen_collected_h.dir/build.make:57: recipe for target 'micropython/CMakeFiles/gen_collected_h' failed
make[2]: *** [micropython/CMakeFiles/gen_collected_h] Error 2
CMakeFiles/Makefile2:651: recipe for target 'micropython/CMakeFiles/gen_collected_h.dir/all' failed
make[1]: *** [micropython/CMakeFiles/gen_collected_h.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

Anyone can help or meet the same issue?

**Comment by willendzw** [comment]
It can be closed. it is due to missing some codes.

**Comment by sueng66** [comment]
what codes ? I have similar problem
