### ISSUE TITLE
MemoryError: Out of normal MicroPython Heap Memory! Please reduce the resolution of the image you are running this algorithm on to bypass this issue!

### ISSUE THREAD

**Issue by diazGT94** [sipeed/MaixPy-v1#393]
I've the following issue.

If i connect my board to the IDE and load my script I get the Memory error, so I need to run an empty script and then run my script and the error is fixed. However, when I tried to burn my script to the boot.py and reset the board I always get that error message and my script doesn't run. I'm already using the gc.collect() method.

Any suggestion of other options I can try?

**Comment by LsDevLab** [comment]
Is there a solution?

**Comment by LsDevLab** [comment]
Solved!
Try to increase gc heap size. I tried with 1000000 (0xF4240) and worked!

```
import Maix
Maix.utils.gc_heap_size(0xF4240)
```

then restart.
