### ISSUE TITLE
could not found sha256_update_length

### ISSUE THREAD

**Issue by sueng66** [sipeed/MaixPy-v1#400]
I couldn't compile after commit 4ac31be because could not find sha256_update_length , what's wrong with mine ?

**Comment by junhuanchen** [comment]
check this https://github.com/sipeed/kendryte-standalone-sdk/tree/7fdb511fe61026eec5874885de5981c4f60f664d

**Comment by sueng66** [comment]
thanks

**Comment by sueng66** [comment]
Should change the kendryte-standalone-sdk to Maixpy-dev branch, not the master one
