### ISSUE TITLE
ValueError: [MAIXPY]kpu: load error:2006, ERR_NO_MEM: memory not enough

### ISSUE THREAD

**Issue by Minelint** [sipeed/MaixPy-v1#417]
I have trained a new kmodel and I run the kmodel in my code
but it return an error code:2006 and remind me 'memory not enough'
I don't know why and how to resolve it
have anybody know?help me please
thanks

**Comment by junhuanchen** [comment]
https://github.com/sipeed/MaixPy/issues?q=memory

**Comment by KuoEuran** [comment]
@Minelint  Have you solved the issue? tks
