### ISSUE TITLE
Error :ValueError:[MAIXPY] kpu:load error:2006 , ERR_No_MEM: memory not enough

### ISSUE THREAD

**Issue by sbabums** [sipeed/MaixPy-v1#422]
**Describe the bug**
When I try to execute the driver program from the MaixPy IDE i get "ValueError:[MAIXPY] kpu:load error:2006 , ERR_No_MEM: memory not enough".

From kpu.memtest(), the following are the outputs:
###free gc heap memory:494 KB
###free sys heap memory:2052 KB

The model size is 3336 KB. 

From the above, i could understand that the size of the model is greater than the free sys heap memory, therefore mem error is encountered. However I want to find a way to resolve this issue. If anybody have faced this issue and if you have tried to solve it , please share the steps. Thanks!!!

**To Reproduce**
1. Using Kflash GUI loaded the model and firmware
2. Using MaixPy IDE executed the driver program after connecting the Maix Dock to the serial port

**Expected behavior**
The driver program should be able to load the model onto flash memory and detect the objects.

**Actual behaviour**
When I try to execute the driver program from the MaixPy IDE i get "ValueError:[MAIXPY] kpu:load error:2006 , ERR_No_MEM: memory not enough".

**Screenshots**

**Please complete the following information**
 - IDE version: [0.2.5]
 - Firmware version: [0.5.0]
 - Board: [Maix  Dock]
 - OS: [Windows]
 - 
![Capture](https://user-images.githubusercontent.com/55679679/120785859-77d76a00-c525-11eb-80ff-873646d612c6.PNG)

**Comment by junhuanchen** [comment]
https://github.com/sipeed/MaixPy/issues?q=memory+not+enough

**Comment by No1possible** [comment]
Replace with a smaller firmware
