### ISSUE TITLE
請問 Normal firmware 如何Import "Speech_recognizer" Library ?

### ISSUE THREAD

**Issue by hungtsosung** [sipeed/MaixPy-v1#424]
您好,
請問Normal firmware: maixpy_v0.6.2_54_g897214100.bin 如何Import "Speech_recognizer" Library ?

 謝謝.
 - IDE version: [Maixpy 0.2.5]
 - Firmware version: [maixpy_v0.6.2_54_g897214100.bin]
 - Board: [Maix Dock] + [6+1 MIC_ARRAY ]
 - OS: [ Windows]

**Comment by STRfarfar** [comment]
将这个固件烧录到开发板上就可以了![image](https://user-images.githubusercontent.com/52208768/127446407-d8bcc7b7-5669-4ebd-ade2-82f946598dbd.png)
https://dl.sipeed.com/shareURL/MAIX/MaixPy/release/master/maixpy_v0.6.2_57_gae955b706
