### ISSUE TITLE
該如何在MaxiPy IDE 上 import tensorflow？

### ISSUE THREAD

**Issue by KuoEuran** [sipeed/MaixPy-v1#428]
**Describe the bug**
該如何使用tensorflow 的API?目前是無法import tensroflow

**Expected behavior**
tensorflow的API可以使用

**Actual behaviour**
無法使用tensorflow的function

**Screenshots**
![image](https://user-images.githubusercontent.com/70742122/129438048-1bad2dca-8bc5-4e04-a167-ee674e7168bf.png)
**Please complete the following information**
 - IDE version: [Maixpy 1.6.7]
 - Firmware version: [0.6.2 latest firmware]
 - Board: [Maix Arduino]
 - OS: [e.g. Windows10]

再麻煩幫忙了謝謝

**Comment by Neutree** [comment]
不支持

**Comment by KuoEuran** [comment]
@Neutree 您好,因為我在https://blog.csdn.net/qq_36229876/article/details/105674765
的部落格上有看到他可以使用tf.image.non_max_suppression的API,但我目前是不知道怎麼使用,請問要用nms的話要如何使用呢?
