### ISSUE TITLE
kpu check image format err

### ISSUE THREAD

**Issue by sahinemreaslan** [sipeed/MaixPy-v1#441]
train stage
https://colab.research.google.com/drive/1UPYZnBF4UzQeZnGl_1TV6MeZ8aOw0dEH

test stage
![image](https://user-images.githubusercontent.com/43322788/140665612-2970114a-96a9-4543-9e28-8b549402147a.png)

 - Board: Maixduino
 - OS: Google Colab and Windows 10

**Comment by Neutree** [comment]
change to 
![image](https://user-images.githubusercontent.com/8625829/140681511-952c45aa-6a14-441d-8638-2bea46478d34.png)

224, 224

**Comment by sahinemreaslan** [comment]
thank you
