### ISSUE TITLE
How to change flash capacity for SPIFFS

### ISSUE THREAD

**Issue by znstj** [sipeed/MaixPy-v1#454]
How to change flash capacity for SPIFFS？
This define in w25qxx.h:
This is 16M Flash,but if ues 128M Flash.How to change it？
#define w25qxx_FLASH_PAGE_SIZE              256
#define w25qxx_FLASH_SECTOR_SIZE            4096
#define w25qxx_FLASH_PAGE_NUM_PER_SECTOR    16
#define w25qxx_FLASH_CHIP_SIZE              (16777216 UL)
Modifying these values ​​has no effect SPIFFS size

**Comment by Neutree** [comment]
python project.py menuconfig

**Comment by znstj** [comment]
> python project.py menuconfig

ERROR:  interesting, something's wrong, boot failed with exit code 233, go to find your vendor.
When I change SPIFFS size in menuconfig
