### ISSUE TITLE
How to flip the video?

### ISSUE THREAD

**Issue by lovettchris** [sipeed/MaixPy-v1#47]
When I mount the camera on the back the video on the screen seems reversed.  When I pan right the video on screen moves left.  Is there a way to flip the video at the driver level to correct for this?  Oddly the same thing still happens even when I add sensor.set_hmirror(1).  I think there's some funky accelerometer based flipping going on because when I rotate the screen the image orientation remains fixed.  This is clever, but I think it needs a way to flip this logic when the camera is mounted on the back...

Also, the flipping is needed for face recognition to work.  Normally face recognizer models do not work on upside down people.  And you can see this happening.  If I add a call to sensor.set_vflip(1) then the recognition starts working, but the image on the screen is flipped.  So I have to flip twice, once before giving to recognizer, then again before display...

**Comment by lovettchris** [comment]
Never mind, I found this method on the sensor:
```python
sensor.set_hmirror(1)
```

**Comment by lovettchris** [comment]
I think I figured it out, this solves both problems:
```
lcd.direction(0x60)
sensor.set_vflip(1)
```

![image](https://user-images.githubusercontent.com/18707114/55598920-0b287100-570a-11e9-9f01-0e2f65ac3d8b.png)

**Comment by Neutree** [comment]
maybe we need to add new api for `lcd.direction()`, it's not good enough

**Comment by zpowellman** [comment]
Hello All,
I have a Maxduino and a Maix Bit. Each is running the latest MaixPY firmware.  I want to set the display to landscape mode.  This code works great on the Maixduino but not on the Maix Bit.

import sensor, lcd
sensor.reset()
sensor.set_pixformat(sensor.RGB565)
sensor.set_framesize(sensor.QVGA)
#sensor.set_hmirror(1)
sensor.set_vflip(1)
sensor.run(1)
sensor.skip_frames()
lcd.init(freq=15000000)
lcd.direction(lcd.YX_LRUD)  # 0x60)
while(True):
    lcd.display(sensor.snapshot())

I'm using the Maix PY IDE and the board types are set accordingly.  I can't make the Maix bit go into landscape, regardless what I do.  Some of the direction constants do weird things on both boards (i.e. 0x40, 0x80, 0xC0).  Any ideas.  I haven't looked into the code yet, maybe this is the time.  I'm using the latest version of 5.0.  Maybe a mistake?
Thanks,
Dan

**Comment by Neutree** [comment]
use `sensor.set_vflip` or `sensor.set_hmirror` or `lcd.rotation` or `lcd.mirror`
