### ISSUE TITLE
name 'fm' isn't defined - when starting through boot.py

### ISSUE THREAD

**Issue by kartur** [sipeed/MaixPy-v1#57]
Try this simple code directly in console and it works fine

`from Maix import GPIO`
`fm.register(board_info.LED_B, fm.fpioa.GPIO0)`
`led_r=GPIO(GPIO.GPIO0,GPIO.OUT)`
`led_r.value(0)`

But when using this code in the boot.py, you get:
> NameError: name 'fm' isn't defined

Using Maix Go and MicroPython v0.3.0-dirty on 2019-04-19

**Comment by robert-hh** [comment]
add upfront:
`from fpioa_manager import fm`
That line is at the top section of _boot.py, A newly created boot.py contains the line:
` from fpioa_manager import *`
So you may simply delete boot.py and then reboot. Then, boot.py will be recreated.

**Comment by kartur** [comment]
I see, thanks.
