### ISSUE TITLE
MaixPy IDE for macOS?

### ISSUE THREAD

**Issue by dongzhixia** [sipeed/MaixPy-v1#65]
Hi, is there a macOS build available?

**Comment by thepian** [comment]
You can build using Docker, I did a dockerfile based on `buildpack-deps:stretch`, it's fairly straight forward.

You might also get it to work straight in macOS mine bombed out in a build script that is probably hardcoded to Linux.

**Comment by Neutree** [comment]
we have no macOS currently..... so... maybe later

**Comment by win32cpp** [comment]
@Neutree I would like to talk to you. Please inform me about your communication.(telegram-whatsapp-facebook-...) .

**Comment by Neutree** [comment]
download here: http://dl.sipeed.com/MAIX/MaixPy/ide/v0.2.2/

**Comment by dongzhixia** [comment]
@Neutree  :thumbsup:

**Comment by thepian** [comment]
I've downloaded this and tried it on all three boards. I see nothing in the framebuffer panes, and cannot connect to the device.

**Comment by KmiloRod** [comment]
> I've downloaded this and tried it on all three boards. I see nothing in the framebuffer panes, and cannot connect to the device.

Same problem here. I'm trying to connect to a Maix Bit with Mic with the last firmware installed (0.3.2) using MaixPy IDE 0.2.4 for macOS, and the Connection dialog just keeps showing "Connecting... Please wait..." without success.

**Comment by Neutree** [comment]
@KmiloRod http://dl.sipeed.com/MAIX/MaixPy/ide/v0.2.4/readme.txt

**Comment by KmiloRod** [comment]
> @KmiloRod http://dl.sipeed.com/MAIX/MaixPy/ide/v0.2.4/readme.txt

Thank you. I loaded firmware 0.4.0_44 and the IDE is working now.

**Comment by mattkanwisher** [comment]
Seems to crash instantly on OS X Catalina. Anyone else have a problem?

**Comment by whatcall** [comment]
> Seems to crash instantly on OS X Catalina. Anyone else have a problem?

Yes, macOS 10.14 crashes too.
I asked help from QQ chat group and they told me the latest release supports up to macOS 10.13.

**Comment by Neutree** [comment]
@whatcall download here: https://dl.sipeed.com/MAIX/MaixPy/ide/v0.2.5 , it compiled on catalina, if problems exist, reopen this issue or create new one
