### ISSUE TITLE
MaixPy and ESP8285 documentation

### ISSUE THREAD

**Issue by amriddell** [sipeed/MaixPy-v1#66]
Hi all,
Is there further documentation and/or example code for the MaiX Go ESP8285?

Thanks.

**Comment by Neutree** [comment]
refer here: https://maixpy.sipeed.com/zh/libs/standard/usocket.html

or you can communicate with 8285 though UART2 by your python code, use AT command

**Comment by robert-hh** [comment]
> refer here: https://maixpy.sipeed.com/zh/libs/standard/usocket.html

Most of the methods documented under that link seem not to be implemented yet, like almost everything that is needed for working as a server (bind(), listen(), accept(), ...)

**Comment by Neutree** [comment]
server mode not implement, same as #68
