### ISSUE TITLE
Maixduino package installation

### ISSUE THREAD

**Issue by amriddell** [sipeed/MaixPy-v1#67]
Wrong link I suspect:

"url": "http://dl.cdn.sipeed.com/MAIX/Maixduino/core/Maixduino_core_v0.3.8.zip"

**Comment by Neutree** [comment]
you can use the resources from dl.sipeed.com, the cdn path are wrong indeed, we will fix it today!

@btx000 the cdn link should be like this if you release:
"http://dl.cdn.sipeed.com/Maixduino_core_v0.3.8.zip"

**Comment by Neutree** [comment]
I'll close this issue, create issue [here](https://github.com/sipeed/Maixduino/issues) all about Maixduino
