### ISSUE TITLE
Rtsp or jpeg stream to pc

### ISSUE THREAD

**Issue by crouse12** [sipeed/MaixPy-v1#70]
I want to send a video stream from a board to PC via Wi-Fi. May I know how to do it?

**Comment by Neutree** [comment]
some steps:

* get image pixels or compressed data

get pixels:

```python
import image

img = image.Image()          # or from sensor.snapshot()
print(img[0:100])                 # pixels with RGB888 format
```

or compressed to JPEG format

```python
import image

img = image.Image()          # or from sensor.snapshot()
img.compress()                  # this will change the source data in img, you can use `img2 = img.compressed()` to create new one object
print(img[0:100])                 # bytes data with JPEG format (tuple)
```

if we want all of the data in `img`, just use `img[:]`


* send it to PC though WiFi

just send data by `socket` module, example refer [here](https://maixpy.sipeed.com/zh/libs/standard/usocket.html#%E4%BE%8B%E7%A8%8B-2%EF%BC%9A-%E5%8F%91%E9%80%81%E5%9B%BE%E7%89%87)

the `img[:]` returns tuple data, maybe you need transfer to `bytearray` type if use `socket.send()`
