### ISSUE TITLE
Add safe overclocking options

### ISSUE THREAD

**Issue by kartur** [sipeed/MaixPy-v1#72]
Currently MaixPy only allows underclocking:
[100, 200, 400]

It would be nice to have at least one safe overclocking option to, e.g., 500 MHz.

**Comment by Neutree** [comment]
add `Maix.freq.set(cpu, pll1, kpu_div)` API in latest commit, see more :[Maix.freq](https://maixpy.sipeed.com/zh/libs/Maix/freq.html)

**Comment by kartur** [comment]
thanks :)
