### ISSUE TITLE
Can't read model from SD card

### ISSUE THREAD

**Issue by WangFengtu1996** [sipeed/MaixPy-v1#78]
if( mbnet.begin(kmodel_name) != 0)
    {
        Serial.println("mobile net init fail");
        Serial.println(mbnet.begin(kmodel_name));
        while(1);
    }
the return Error num is -4.

**Comment by Neutree** [comment]
* check SD by SD card demo
* filename do not too long `const char* kmodel_name = "m";` for example
* Create issue in Maixduino repo please!!
