### ISSUE TITLE
Any AI examples in the MaixPy library?

### ISSUE THREAD

**Issue by Tylersuard** [sipeed/MaixPy-v1#79]
Hello!  I love the price and capabilities of the MAIX, seriously considering getting one.  My main language is Micropython, I'm not seeing any machine learning demos in your examples folder for the micropython version?  I was hoping to see some examples that could detect faces, detect if someone is smiling, etc.  Thanks!

**Comment by Neutree** [comment]
now we haven't provide so much model, you can try to train the model yourself. and then load it with maixpy to run

**Comment by Neutree** [comment]
like [hardware.ai](https://www.youtube.com/watch?v=fZ4QbtAjKXo) ( [article](https://www.instructables.com/id/Transfer-Learning-With-Sipeed-MaiX-and-Arduino-IDE/) ) did

**Comment by Neutree** [comment]
face recognition: https://github.com/sipeed/MaixPy_scripts/blob/master/machine_vision/demo_face_recognition.py
find face: https://github.com/sipeed/MaixPy_scripts/blob/master/machine_vision/demo_find_face.py
more: https://github.com/sipeed/MaixPy_scripts/tree/master/machine_vision
more models: https://www.maixhub.com/
