### ISSUE TITLE
REQUEST: Firmware minimum supports MaisPy IDE

### ISSUE THREAD

**Issue by laurentopia** [sipeed/MaixPy-v1#86]
Currently the minimum firmware removes OpenMV andthe GUI library, which is perfect for pure NN work but the MaixPY IDE doesn't connect to it. This is probably due to OpenMV itself including the connection code (since the MaixPy IDE is a fork of the OpenMV IDE)
It would be great that this part of the OpenMV library be extracted as a stand alone.

**Comment by Neutree** [comment]
The minimum firmware won't support IDE，In the future we can add compile options, you compile and generate the required firmware yourself.
