### ISSUE TITLE
Putty returning garbage

### ISSUE THREAD

**Issue by laurentopia** [sipeed/MaixPy-v1#87]
Putty was working fine, then I uploaded a new firmware and now I'm getting this
![image](https://user-images.githubusercontent.com/26075468/58363454-45380880-7e59-11e9-9501-5f449fdd815a.png)

It happens with all 0.3.2 and 0.3.1 full

settings:
![image](https://user-images.githubusercontent.com/26075468/58363474-79abc480-7e59-11e9-90ca-fe24bc99b346.png)

**Comment by Neutree** [comment]
it's strange, it remains exist in latest master firmware or not? or try other tool

close this issue for it may out of date, I tried on my PC, it's no problem
