### ISSUE TITLE
asmledpy not working

### ISSUE THREAD

**Issue by laurentopia** [sipeed/MaixPy-v1#88]
![image](https://user-images.githubusercontent.com/26075468/58364584-94873480-7e6b-11e9-88e8-55a01b351521.png)

This is from the maixpy IDE

**Comment by Neutree** [comment]
maixpy not support

**Comment by laurentopia** [comment]
This was in https://github.com/sipeed/MaixPy/tree/master/examples which contains only non working examples, I think it was left from the forking of micropython you guys did. It'd be better deleted I think.

**Comment by dimitre** [comment]
+1 for deleting. I've tried several examples in this github and they are broken.

**Comment by Neutree** [comment]
micropython now as a submodule
