### ISSUE TITLE
Cannot run qr code demo and touchscreen demo

### ISSUE THREAD

**Issue by hrshovon** [sipeed/MaixPy-v1#91]
hello,
I am running maixpy 0.3.2
demo_scan_qr_code.py does not work.
If I try to run it, I get no module named "clock"

I tried running the touchscreen demo code from maixpy documentation.
I get "board_info is not callable"

**Comment by Neutree** [comment]
```python
import time

clock = time.clock()
```

````python
from fpioa_manager import board_info

```
