### ISSUE TITLE
Running non image models

### ISSUE THREAD

**Issue by hrshovon** [sipeed/MaixPy-v1#93]
Hello,
Recently I saw from nncase repository that they have implemented non image float input feature for models. They also provided a demo code written in their cpp sdk. https://github.com/kendryte/nncase/tree/master/examples/iris

Can I do the same in python now? I tried loading the model provided here. It loaded but I could not run kpu.forward using a list of features like [5.1,3.8,1.9,0.4], probably because of the mismatch between data types. 
How can I perform inference using this model in python?

**Comment by Neutree** [comment]
support in e6211b43d27f895fef67c31b7b615604d146fffe
