### ISSUE TITLE
How to resize the image from sensor.snapshot?

### ISSUE THREAD

**Issue by carry-xz** [sipeed/MaixPy-v1#96]
hello! How to resize the image from sensor.snapshot?  thanks!
I want to calculate/save in one resolution and show in LCD in other resolution

**Comment by Neutree** [comment]
maybe image.resize(width, height) can help you ?
e.g.
```
img = sensor.snapshot()
img = img.resize()
```

**Comment by shanejohnpaul** [comment]
Is there a resize function? I don't see it anywhere.

**Comment by Neutree** [comment]
![image](https://user-images.githubusercontent.com/8625829/91009326-f4dac800-e612-11ea-8469-aeca4834f09b.png)

**Comment by shanejohnpaul** [comment]
Could you point me to where the source code is for this function?

**Comment by Neutree** [comment]
py_image.c py_image_resize function
